= Identity によるアクセス制御を追加する
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
//:!page-repl:
:proglang: Motoko
:LEE: ローカル Canister 実行環境
:IC: Internet Computer blockchain
:company-id: DFINITY


Dapp では、ユーザーごとに操作を制御するために、ロールベースのパーミッションが必要になることがよくあります。

このチュートリアルでは、ユーザー identity の作成と切り替え方法を解説するために、異なるロールを割り当てられたユーザーに対して、異なる挨拶を表示する簡単な Dapp を作成します。

この例では、`+owner+`、`+admin+`、`+authorized+` という名前の３つのロールが存在します。

* `+admin+` ロールが割り当てられたユーザーには、`+You have a role with administrative privileges+`（あなたは管理者権限のあるロールを持っています）という挨拶が表示されます。
* `+authorized+` ロールが割り当てられたユーザーには、`+Would you like to play a game?+`（ゲームをしたいですか？）という挨拶が表示されます。
* これらのロールが割り当てられていないユーザーには、`+Nice to meet you!+`（はじめまして！） という挨拶が表示されます。

さらに、Canister スマートコントラクトを初期化した ユーザー Identity にのみ `+owner+` ロールが割り当てられ、`+owner+` と `+admin+` ロールのみ他のユーザーにロールを割り当てることができます。

大まかに言えば、各ユーザーは公開鍵/秘密鍵のペアを持ちます。公開鍵と、ユーザーがアクセスする Canister スマートコントラクト識別子を組み合わせて、セキュリティ Principal を形成し、{IC} 上で動作する Canister スマートコントラクトへの関数呼び出しを認証するメッセージ呼び出し元として使用できます。
下図で、ユーザー Identity がメッセージ呼び出し元を認証する方法を簡略化して示します。

image::principal-identities.svg[]

== 始める前に

チュートリアルを始める前に、下記を確認してください。

* link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール] の説明に従って {sdk-short-name} パッケージをダウンロードし、インストールした。

* 少なくとも１つのコマンドを実行し、`+default+` ユーザーの Identity が作成された。
デフォルトのユーザー Identity は、すべてのプロジェクトにおいて `+$HOME/.config/dfx/identity/+` ディレクトリにグローバルに保存されます。

* IDE としてVisual Studio Code を使用している場合、link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] で説明したように、{proglang} 用の Visual Studio Code プラグインをインストールした。

* コンピュータ上で実行されている {LEE} プロセスをすべて停止した。

== 新規プロジェクトを作成する

アクセス制御とユーザー Identity の切り替えをテストするために、新規プロジェクトディレクトリを作成するには

. ローカルコンピューターでターミナルシェルを開いてください（まだ開いていない場合）。
. {IC} プロジェクトで使用しているフォルダがある場合は、そのフォルダに移動します。
. 下記コマンドを実行することで、新規プロジェクトを作成します。
+
[source,bash]
----
dfx new access_hello
----
. 以下のコマンドを実行することで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd access_hello
----

== デフォルトの Dapp を変更する

このチュートリアルでは、テンプレートのソースコードファイルを、ロールの割り当てと取得のための機能を持つ Dapp に置き換えます。

デフォルトの Dapp を変更するには

. テキストエディタで `+src/access_hello/main.mo+` ファイルを開き、既存の内容を削除します。
. 下記のサンプルコードをコピーしてファイルに貼り付けます。
+
[source.copy,motoko,no-repl]
----
include::example$access-hello/main.mo[]
----
+
この Dapp の主要な要素をいくつか見てみましょう。
+
--
* `+greet+` 関数は、以前のチュートリアルで見た `+greet+` 関数のバリエーションであることにお気づきかもしれません。
+
しかし、この Dapp では、`+greet+` 関数がメッセージの呼び出し元を利用して、適用すべきパーミッションを決定し、呼び出し元に関連するパーミッションに基づいて、どの挨拶を表示するかを決めます。
* この Dapp では、`+Roles+` と `+Permissions+` の２つのカスタム型を定義します。
* `+assign_roles+` 関数を使用すると、メッセージの呼び出し元が Identity に関連付けられた Principal にロールを割り当てることができます。
* `+callerPrincipal+` 関数を使用すると、Identity に関連付けられた Principal を返せます。
* `+my_role+` 関数を使用すると、Identity に関連付けられたロールを返せます。
--
. 変更を保存し、`+main.mo+` ファイルを閉じて、続行します。

== Start the {LEE} / {LEE} を起動する

`+access_hello+` プロジェクトをビルドする前に、開発環境で動作している {LEE} または {IC} のメインネットに接続する必要があります。

{LEE} を起動するには

. ローカルコンピューターで新しいターミナルウィンドウまたはタブを開きます。
. 必要であれば、プロジェクトのルートディレクトリに移動します。
. 下記のコマンドを実行することで、コンピュータ上の {LEE} を起動します。
+
[source,bash]
----
dfx start --background
----
+
{LEE} の起動操作が完了したら、次の手順に進めます。

== Dapp を登録、ビルド、デプロイする

開発環境で動作している {LEE} に接続した後、link:../cli-reference/dfx-deploy{outfilesuffix}[`dfx deploy`] コマンドを実行することで、Dapp の登録、構築、デプロイが一度で行えます。
link:../cli-reference/dfx-canister{outfilesuffix}#dfx_canister_create[`+dfx canister create+`]、link:../cli-reference/dfx-build{outfilesuffix}[`+dfx build+`]、および link:../cli-reference/dfx-canister{outfilesuffix}#dfx_canister_install[`+dfx canister install+`] コマンドを用いてこれらの各ステップを個別に実行することも可能です。

Dapp をローカルにデプロイするには

. 必要に応じて、プロジェクトのルートディレクトリにまだいることを確認します。
. 下記のコマンドを実行することで、`+access_hello+` バックエンド Dapp を登録、ビルド、デプロイします。
+
[source,bash]
----
dfx deploy access_hello
----
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying: access_hello
Creating canisters...
Creating canister "access_hello"...
"access_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Installing canisters...
Installing code for canister access_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
....

== 現在の Identity コンテキストを確認する

追加の Identity を作成する前に、`+default+` Identity と `+default+` Identity 用の Cycle ウォレットに関連付けられた Principal 識別子を確認しましょう。
{IC} において、Principal はユーザー、Canister スマートコントラクト、ノード、またはサブネットの内部の代表です。Principal のテキスト表現は、Principal データ型で作業している際に表示される外部識別子です。

現在の Identity と Principal を確認するには

. 下記のコマンドを実行することで、現在アクティブな Identity を確認します。
+
[source,bash]
----
dfx identity whoami
----
+
このコマンドは、下記のような出力を表示します。
+
....
default
....
. 下記のコマンドを実行することで、`+default+` ユーザー Identity の Principal を確認します。
+
[source,bash]
----
dfx identity get-principal
----
+
このコマンドは、下記のような出力を表示します。
+
....
zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe
....
. 下記のコマンドを実行することで、`+default+` ユーザー Identity に関連付けられたロールを確認します。
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello my_role
----
+
このコマンドは、下記のような出力を表示します。
+
....
(opt variant { owner })
....

== 新しいユーザー Identity を作成する

Dapp のアクセス制御のテストを始めるために、いくつかの新しいユーザー Identity を作成し、それらのユーザーに異なるロールを割り当てましょう。

新しいユーザー Identity を作成するには

. 必要に応じて、プロジェクトのディレクトリにまだいることを確認します。
. 下記のコマンドを実行することで、新しい管理ユーザー Identity を作成します。
+
[source,bash]
----
dfx identity new ic_admin
----
+
このコマンドは、下記のような出力を表示します。
+
....
Creating identity: "ic_admin".
Created identity: "ic_admin".
....
. 新しいユーザー Identity がどのロールにも割り当てられていないことを確認するために、`+my_role+` 関数を呼び出してください。
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
このコマンドは、下記のような出力を表示します。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "ic_admin" is "ryjl3-tyaaa-aaaaa-aaaba-cai"
(null)
....
. 下記のコマンドを実行することで、新しい `+ic_admin+` ユーザー Identity を使用するために現在のアクティブ Identity コンテキストを切り替えて、`+ic_admin+` ユーザーに関連付けられている Principal を表示します。
+
[source,bash]
----
dfx identity use ic_admin && dfx identity get-principal
----
+
このコマンドは、下記のような出力を表示します。
+
....
Using identity: "ic_admin".
c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae
....
. 下記のコマンドを実行することで、`+access_hello+` Canister スマートコントラクトを呼び出すのに使用される Principal を確認します。
+
[source,bash]
----
dfx canister call access_hello callerPrincipal
----
+
このコマンドは、下記のような出力を表示します。
+
....
(principal "ryjl3-tyaaa-aaaaa-aaaba-cai")
....
+
デフォルトでは、Cycles ウォレットの識別子は、`+access_hello+` Canister スマートコントラクトのメソッドを呼び出すのに使用される Principal です。
しかし、アクセス制御を解説するために、Cycle ウォレットではなく、ユーザーコンテキストに関連付けられた Principal 使用したいと思います。
しかし、その前に `+ic_admin+` ユーザーに対してロールを割り当てましょう。そのためには、`+owner+` ロールを持つ `+default+` ユーザー Identity に切り替える必要があります。

== Identity にロールを割り当てる

ic_admin Identity に admin ロールを割り当てるには

. 下記のコマンドを実行することで、現在アクティブな Identity コンテキストを切り替えることで、`+default+` ユーザー Identity を使用するようにします。
+
[source,bash]
----
dfx identity use default
----
. コマンドを下記のような Candid 構文で実行することで、`+ic_admin+` Principal に `+admin+` ロールを割り当てます。
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello assign_role '((principal "c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae"),opt variant{admin})'
----

NOTE: 必ず `+principal+` ハッシュを、`+ic_admin+` Identity の `+dfx identity get-principal+` コマンドによって返されるハッシュに置き換えてください。

+
オプションとして、コマンドを再実行して `+my_role+` 関数を呼び出し、ロールの割り当てを確認できます。
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
このコマンドは、下記のような出力を表示します。
+
....
(opt variant { admin })
....
. 先ほど `+admin+` ロールを割り当てた `+ic_admin+` ユーザー Identity を使用して、下記のコマンドを実行することで、`+greet+` 関数を呼び出します。
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello greet "Internet Computer Admin"
----
+
このコマンドは、下記のような出力を表示します。
+
....
(
  "Hello, Internet Computer Admin. You have a role with administrative privileges.",
)
....

== authorized ユーザー Identity を追加する

この時点で、`+default+` ユーザー Identity に `+owner+` ロール、 `+ic_admin+` ユーザー Identity に `+admin+` ロールを割り当てました。
もう１つユーザー Identity を追加して、 `+authorized+` ロールを割り当てましょう。
ただし、この例では、ユーザーの Principal を格納するのに環境変数を使用します。

新しい authorized ユーザー Identity を追加するには

. 必要に応じて、プロジェクトディレクトリにまだいることを確認します。
. 下記のコマンドを実行することで、新しい authorized ユーザー Identity を作成します。
+
[source,bash]
----
dfx identity new alice_auth
----
+
このコマンドは、下記のような出力を表示します。
+
....
Creating identity: "alice_auth".
Created identity: "alice_auth".
....
. 下記のコマンドを実行することで、現在アクティブな Identity コンテキストを切り替えて、新しい `+alice_auth+` ユーザー Identity を使用するようにします。
+
[source,bash]
----
dfx identity use alice_auth
----
. 下記のコマンドを実行することで、`+alice_auth+` ユーザーの Principal を環境変数に格納します。
+
[source,bash]
----
ALICE_ID=$(dfx identity get-principal)
----
+
下記のコマンドを実行することで、保存されている Principal を確認できます。
+
[source,bash]
----
echo $ALICE_ID
----
+
このコマンドは、下記のような出力を表示します。
+
....
b5quc-npdph-l6qp4-kur4u-oxljq-7uddl-vfdo6-x2uo5-6y4a6-4pt6v-7qe
....
+
. `+ic_admin+` の Identity を使用して、下記のコマンドを実行することで `+alice_auth+` に `+authorized+` ロールを割り当てます。
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello assign_role "(principal \"$ALICE_ID\", opt variant{authorized})"
----
. ロールの割り当てを確認するために `+my_role+` 関数を呼び出します。
+
[source,bash]
----
dfx --identity alice_auth canister call access_hello my_role
----
このコマンドは、下記のような出力を表示します。
+
....
(opt variant { authorized })
....
. 先ほど `+authorized+` ロールを割り当てた `+alice_auth+` ユーザー Identity を使用して、下記のコマンドを実行することで `+greet+` 関数を呼び出してください。
+
[source,bash]
----
dfx canister call access_hello greet "Alice"
----
+
このコマンドは、下記のような出力を表示します。
+
....
(
  "Welcome, Alice. You have an authorized account. Would you like to play a game?",
)
....

== unauthorized なユーザー Identity を追加する

ここまで、特定のロールとパーミッションのあるユーザーを作成する簡単な例を見ました。
次のステップでは、ロールが割り当てられていない、または特別なパーミッションが与えられていないユーザー・アイデンティティを作成します。

unauthorized なユーザー Identity を追加するには

. 必要に応じて、プロジェクトディレクトリにまだいることを確認します。
. 必要に応じて、下記のコマンドを実行することで、現在アクティブな Identity を確認します。
+
[source,bash]
----
dfx identity whoami
----
. 下記のコマンドを実行することで、新しいユーザー Identity を作成します。
+
[source,bash]
----
dfx identity new bob_standard
----
+
このコマンドは、下記のような出力を表示します。
+
....
Creating identity: "bob_standard".
Created identity: "bob_standard".
....
. 以下のコマンドを実行することで、`+bob_standard+` ユーザーの Principal を環境変数に格納します。
+
[source,bash]
----
BOB_ID=$(dfx --identity bob_standard identity get-principal)
----
. ロールを割り当てるために `+bob_standard+` Identity を使用してみます。
+
[source,bash]
----
dfx --identity bob_standard canister call access_hello assign_role "(principal \"$BOB_ID\", opt variant{authorized})"
----
+
このコマンドは `+Unauthorized+` エラーを返します。
. 下記のコマンドを実行することで、`+default+` ユーザー Identity を使用して `+bob_standard+` に `+owner+` ロールを割り当ててみます。
+
[source,bash]
----
dfx --identity default canister --wallet=$(dfx --identity default identity get-wallet) call access_hello assign_role "(principal \"$BOB_ID\", opt variant{owner})"
----
+
このコマンドは、ユーザーに `+owner+` ロールを割り当てることができないため、失敗します。
. 下記のコマンドを実行することで、`+bob_standard+` ユーザー Identity を使用して `+greet+` 関数を呼び出します。
+
[source,bash]
----
dfx --identity bob_standard canister call access_hello greet "Bob"
----
+
このコマンドは、下記のような出力を表示します。
+
....
("Greetings, Bob. Nice to meet you!")
....

== 複数のコマンドでユーザー Identity を設定する

ここまで、個々のコマンドでユーザー Identity を作成し、切り替える方法について見てきました。
使用したいユーザー Identity を指定し、そのユーザー Identity のコンテキストで複数のコマンドを実行することも可能です。

１つのユーザー Identity で複数のコマンドを実行するには

. 必要であれば、プロジェクトディレクトリにまだいることを確認します。
. 下記のコマンドを実行することで、現在利用可能なユーザー Identity を一覧表示します。
+
[source,bash]
----
dfx identity list
----
+
このコマンドは、現在アクティブなユーザー Identity を示すアスタリスクと共に、下記のような出力を表示します。
+
....
alice_auth
bob_standard
default *
ic_admin
....
+
この例では、明示的に別の Identity を選択しない限り、`+default+` ユーザー Identity が使用されます。
. 下記のようなコマンドを実行することで、一覧から新しいユーザー Identity を選択し、それをアクティブなユーザーコンテキストにします。
+
[source,bash]
----
dfx identity use ic_admin
----
+
このコマンドは、下記のような出力を表示します。
+
....
Using identity: "ic_admin".
....
+
`+dfx identity list+` コマンドを再実行すると、`+ic_admin+` ユーザー Identity が現在アクティブなユーザーコンテキストであることを示すアスタリスクが表示されます。

+
コマンドラインで `+--identity+` を指定しなくても、選択したユーザー Identity を使用してコマンドを実行できるようになります。

== {LEE} を停止する

Dapp の実体験と Identity の使用が終わったら、バックグラウンドで動作し続けないように {LEE} を停止できます。

{LEE} を停止するには

. ネットワーク操作を表示するターミナルで、Control-C を押して、ローカルネットワークの処理を中断します。
. 下記のコマンドを実行することで、{LEE} を停止します。
+
[source,bash]
----
dfx stop
----

== もっと詳しく知りたいですか？

Identity と認証についてより詳しい情報をお探しの場合は、下記の関連資料をご覧ください。

* link:../cli-reference/dfx-identity{outfilesuffix}[dfx identity（コマンドリファレンス）]
* link:../working-with-canisters{outfilesuffix}#set-owner[Canister スマートコントラクトを所有するための Identity を設定する（ハウツー）]

////
= Add access control with identities
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
//:!page-repl:
:proglang: Motoko
:LEE: local canister execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY

Dapps often require role-based permissions to control the operations different users can perform.

To illustrate how to create and switch between user identities, this tutorial creates a simple dapp that displays a different greeting for users who are assigned to different roles.

In this example, there are three named roles—`+owner+`, `+admin+`, and `+authorized+`. 

* Users who are assigned an `+admin+` role see a greeting that displays `+You have a role with administrative privileges+`.
* Users who are assigned an `+authorized+` role see a greeting that displays `+Would you like to play a game?+`.
* Users who are not assigned one of these roles see a greeting that displays `+Nice to meet you!+`.

In addition, only the user identity that initialized the canister smart contract is assigned the `+owner+` role and only the `+owner+` and `+admin+` roles can assign roles to other users.

At a high-level, each user has a public/private key pair. The public key combined with the canister smart contract identifier the user accesses forms a security principal that can then be used as a message caller to authenticate function calls made to the canister smart contract running on the {IC}.
The following diagram provides a simplified view of how user identities authenticate message callers.

image::principal-identities.svg[]

== Before you begin

Before starting the tutorial, verify the following:

* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have run at least one command that resulted in your `+default+` user identity being created. 
Your default user identity is stored globally for all projects in the `+$HOME/.config/dfx/identity/+` directory.

* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are using Visual Studio Code as your IDE.

* You have stopped any {LEE} processes running on your computer.

== Create a new project

To create a new project directory for testing access control and switching user identities:

. Open a terminal shell on your local computer, if you don’t already have one open.
. Change to the folder you are using for your {IC} projects, if you are using one.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new access_hello
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd access_hello
----

== Modify the default dapp

For this tutorial, you are going to replace the template source code file with a dapp that has functions for assigning and retrieving roles.

To modify the default dapp:

. Open the `+src/access_hello/main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the file:
+
[source.copy,motoko,no-repl]
----
include::example$access-hello/main.mo[]
----
+
Let's take a look at a few key elements of this dapp:
+
--
* You might notice that the `+greet+` function is a variation on the `+greet+` function you have seen in previous tutorials. 
+
In this dapp, however, the `+greet+` function uses a message caller to determine the permissions that should be applied and, based on the permissions associated with the caller, which greeting to display.
* The dapp defines two custom types—one for `+Roles+` and one for `+Permissions+`.
* The `+assign_roles+` function enables the message caller to assign a role to the principal associated with an identity.
* The `+callerPrincipal+` function enables you to return the principal associated with an identity.
* The `+my_role+` function enables you to return the role that is associated with an identity.
--
. Save your changes and close the `+main.mo+` file to continue.

== Start the {LEE}

Before you can build the `+access_hello+` project, you need to connect to the {LEE} running in your development environment or to the {IC} mainnet.

To start the {LEE}:

. Open a new terminal window or tab on your local computer.
. Navigate to the root directory for your project, if necessary.
. Start the {LEE} on your computer by running the following command:
+
[source,bash]
----
dfx start --background
----
+
After the {LEE} completes its startup operations, you can continue to the next step.

== Register, build, and deploy the dapp

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your dapp in a single step by running the link:../cli-reference/dfx-deploy{outfilesuffix}[`dfx deploy`] command.
You can also perform each of these steps independently using separate link:../cli-reference/dfx-canister{outfilesuffix}#dfx_canister_create[`+dfx canister create+`], link:../cli-reference/dfx-build{outfilesuffix}[`+dfx build+`], and link:../cli-reference/dfx-canister{outfilesuffix}#dfx_canister_install[`+dfx canister install+`] commands.

To deploy the dapp locally:

. Check that you are still in the root directory for your project, if needed.
. Register, build, and deploy the `+access_hello+` back-end dapp by running the following command:
+
[source,bash]
----
dfx deploy access_hello
----
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying: access_hello
Creating canisters...
Creating canister "access_hello"...
"access_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Installing canisters...
Installing code for canister access_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
....

== Check the current identity context

Before we create any additional identities, let's review the principal identifiers associated with your `+default+` identity and the cycles wallet for your `+default+` identity.
On the {IC}, a principal is the internal representative for a user, canister smart contract, node, or subnet. The textual representation for a principal is the external identifier you see displayed with working with the principal data type.

To review your current identity and principle:

. Verify the currently-active identity by running the following command:
+
[source,bash]
----
dfx identity whoami
----
+
The command displays output similar to the following:
+
....
default
....
. Check the principal for the `+default+` user identity by running the following command:
+
[source,bash]
----
dfx identity get-principal
----
+
The command displays output similar to the following:
+
....
zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe
....
. Check the role associated with the `+default+` user identity by running the following command:
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello my_role
----
+
The command displays output similar to the following:
+
....
(opt variant { owner })
....

== Create a new user identity

To begin testing the access controls in our dapp, let's create some new user identities and assign those users to different roles.

To create a new user identity:

. Check that you are still in your project directory, if needed.
. Create a new administrative user identity by running the following command:
+
[source,bash]
----
dfx identity new ic_admin
----
+
The command displays output similar to the following:
+
....
Creating identity: "ic_admin".
Created identity: "ic_admin".
....
. Call the `+my_role+` function to see that your new user identity has not been assigned to any role.
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
The command displays output similar to the following:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "ic_admin" is "ryjl3-tyaaa-aaaaa-aaaba-cai"
(null)
....
. Switch your currently-active identity context to use the new `+ic_admin+` user identity and display the principal associated with the `+ic_admin+` user by running the following command:
+
[source,bash]
----
dfx identity use ic_admin && dfx identity get-principal
----
+
The command displays output similar to the following:
+
....
Using identity: "ic_admin".
c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae
....
. Check the principal used to call the `+access_hello+` canister smart contract by running the following command:
+
[source,bash]
----
dfx canister call access_hello callerPrincipal
----
+
The command displays output similar to the following:
+
....
(principal "ryjl3-tyaaa-aaaaa-aaaba-cai")
....
+
By default, the cycles wallet identifier is the principal used to call the methods in the `+access_hello+` canister smart contract.
To illustrate access control, however, we want to use the principal associated with the user context, not the cycles wallet.
Before we get to that step, though, let's assign a role to the `+ic_admin+` user. To do that, we need to switch to the `+default+` user identity that has the `+owner+` role.

== Assign a role to an identity

To assign the admin role to the ic_admin identity:

. Switch your currently-active identity context to use the `+default+` user identity by running the following command:
+
[source,bash]
----
dfx identity use default
----
. Assign the `+ic_admin+` principal the `+admin+` role by running a command similar to the following using Candid syntax:
+
[source,bash]
----
dfx canister --wallet=$(dfx identity get-wallet) call access_hello assign_role '((principal "c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae"),opt variant{admin})'
----

NOTE: Be sure to replace the `+principal+` hash with the one returned by the `+dfx identity get-principal+` command for the `+ic_admin+` identity.

+
Optionally, you can rerun the command to call the `+my_role+` function to verify the role assignment.
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello my_role
----
+
The command displays output similar to the following:
+
....
(opt variant { admin })
....
. Call the `+greet+` function using the `+ic_admin+` user identity that you just assigned the `+admin+` role by running the following command:
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello greet "Internet Computer Admin"
----
+
The command displays output similar to the following:
+
....
(
  "Hello, Internet Computer Admin. You have a role with administrative privileges.",
)
....

== Add an authorized user identity

At this point, you have a `+default+` user identity with the `+owner+` role and an `+ic_admin+` user identity with the `+admin+` role. 
Let's add another user identity and assign it to the `+authorized+` role. 
For this example, however, we'll use an environment variable to store the user's principal.

To add a new authorized user identity:

. Check that you are still in your project directory, if needed.
. Create a new authorized user identity by running the following command:
+
[source,bash]
----
dfx identity new alice_auth
----
+
The command displays output similar to the following:
+
....
Creating identity: "alice_auth".
Created identity: "alice_auth".
....
. Switch your currently-active identity context to use the new `+alice_auth+` user identity by running the following command:
+
[source,bash]
----
dfx identity use alice_auth
----
. Store the principal for the `+alice_auth+` user in an environment variable by running the following command:
+
[source,bash]
----
ALICE_ID=$(dfx identity get-principal)
----
+
You can verify the principal stored by running the following command:
+
[source,bash]
----
echo $ALICE_ID
----
+
The command displays output similar to the following:
+
....
b5quc-npdph-l6qp4-kur4u-oxljq-7uddl-vfdo6-x2uo5-6y4a6-4pt6v-7qe
....
+
. Use the `+ic_admin+` identity to assign the `+authorized+` role to `+alice_auth+` by running the following command:
+
[source,bash]
----
dfx --identity ic_admin canister call access_hello assign_role "(principal \"$ALICE_ID\", opt variant{authorized})"
----
. Call the `+my_role+` function to verify the role assignment.
+
[source,bash]
----
dfx --identity alice_auth canister call access_hello my_role
----
The command displays output similar to the following:
+
....
(opt variant { authorized })
....
. Call the `+greet+` function using the `+alice_auth+` user identity that you just assigned the `+authorized+` role by running the following command:
+
[source,bash]
----
dfx canister call access_hello greet "Alice"
----
+
The command displays output similar to the following:
+
....
(
  "Welcome, Alice. You have an authorized account. Would you like to play a game?",
)
....

== Add an unauthorized user identity

You have now seen a simple example of creating users with specific roles and permissions.
The next step is to create a user identity that is not assigned to a role or given any special permissions.

To add an unauthorized user identity:

. Check that you are still in your project directory, if needed.
. Check your currently-active identity, if needed, by running the following command:
+
[source,bash]
----
dfx identity whoami
----
. Create a new user identity by running the following command:
+
[source,bash]
----
dfx identity new bob_standard
----
+
The command displays output similar to the following:
+
....
Creating identity: "bob_standard".
Created identity: "bob_standard".
....
. Store the principal for the `+bob_standard+` user in an environment variable by running the following command:
+
[source,bash]
----
BOB_ID=$(dfx --identity bob_standard identity get-principal)
----
. Attempt to use the `+bob_standard+` identity to assign a role.
+
[source,bash]
----
dfx --identity bob_standard canister call access_hello assign_role "(principal \"$BOB_ID\", opt variant{authorized})"
----
+
This command returns an `+unauthorized+` error.
. Attempt to use the `+default+` user identity to assign `+bob_standard+` the `+owner+` role by running the following command:
+
[source,bash]
----
dfx --identity default canister --wallet=$(dfx --identity default identity get-wallet) call access_hello assign_role "(principal \"$BOB_ID\", opt variant{owner})"
----
+
This command fails because users cannot be assigned the `+owner+` role.
. Call the `+greet+` function using the `+bob_standard+` user identity by running the following command:
+
[source,bash]
----
dfx --identity bob_standard canister call access_hello greet "Bob"
----
+
The command displays output similar to the following:
+
....
("Greetings, Bob. Nice to meet you!")
....

== Set the user identity for multiple commands

So far, you have seen how to create and switch between user identities for individual commands. 
You can also specify a user identity you want to use, then run multiple commands in the context of that user identity.

To run multiple commands under one user identity:

. Check that you are still in your project directory, if needed.
. List the user identities currently available by running the following command:
+
[source,bash]
----
dfx identity list
----
+
The command displays output similar to the following with an asterisk indicating the currently-active user identity.
+
....
alice_auth
bob_standard
default *
ic_admin
....
+
In this example, the `+default+` user identity is used unless you explicitly select a different identity.
. Select a new user identity from the list and make it the active user context by running a command similar to the following:
+
[source,bash]
----
dfx identity use ic_admin
----
+ The command displays output similar to the following:
+
....
Using identity: "ic_admin".
....
+
If you rerun the `+dfx identity list+` command, the `+ic_admin+` user identity displays an asterisk to indicate it is the currently active user context.
+
You can now run commands using the selected user identity without specifying `+--identity+` on the command-line. 

== Stop the {LEE}

After you finish experimenting with the dapp and using identities, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the local network process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----

== Want to learn more?

If you are looking for more information about identity and authentication, check out the following related resources:

* link:../cli-reference/dfx-identity{outfilesuffix}[dfx identity (command reference)]
* link:../working-with-canisters{outfilesuffix}#set-owner[Set an identity to own a canister smart contract (how-to)]
////
