= Web アプリ開発セキュリティ・ベストプラクティス

== 認証

=== 監査済みの認証サービスとクライアントサイド  IC ライブラリを使用する

==== セキュリティ上の懸念事項

Web アプリでユーザー認証や Canister コールを自分で実装するのは、エラーが起こりやすくリスクが高いです。例えば、Canister コールをゼロから実装した場合、署名の作成や検証に関するバグが発生する可能性があります。

==== 推奨

- 認証には link:https://github.com/dfinity/internet-identity[Internet Identity] などを使用し、Canister コールには link:https://github.com/dfinity/agent-js[agent-js]、Dapp から Internet Identity と対話するには link:https://github.com/dfinity/agent-js/tree/main/packages/auth-client[auth-client] を使用することを考えてみてください。
- もちろん、認証のために IC 上の代替認証フレームワークを検討することもオプションの一つです。

=== 適切なセッションタイムアウトを設定する

==== セキュリティ上の懸念事項

現在、Internet Identity は有効期限付きの委任を発行しています。この有効期限は、 link:https://github.com/dfinity/agent-js/tree/main/packages/auth-client[auth-client] で設定することができます。委任の有効期限が切れると、ユーザーは再認証する必要があります。適切な値を設定することは、セキュリティとユーザビリティのトレードオフです。

==== 推奨

link:https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-expiration[OWASP Recommendations] を参照してください。セキュリティに敏感なアプリケーションでは、30分のタイムアウトを設定する必要があります。

Note：アイドルタイムアウトは近々導入されるかもしれません。link:https://forum.dfinity.org/t/authclient-update-idle-timeouts/10464[ここ] を参照してください。

=== 運用中の agent-js で fetchRootKey を使用しない

==== セキュリティ上の懸念事項

link:https://github.com/dfinity/agent-js[agent-js] で `agent.fetchRootKey()` を使用すると、テスト環境において、ステータスコールからルートサブネット閾値公開鍵を取得することが可能です。この鍵は Canister のアップデートコールで受信した認証データの閾値署名を検証するために使用されます。この方法をプロダクション環境の Web アプリで使用すると、攻撃者は自分の公開鍵を提供することができ、アップデートレスポンスのすべての信頼性保証を無効にすることができます。

==== 推奨

実運用環境では決して `agent.fetchRootKey()` を使用せず、テストビルドのときだけ使用します。このメソッドを呼び出さない場合、ハードコーディングされたメインネットのルートサブネット公開鍵が署名検証に使用されることになります。

== Internet Computer に特有でなく一般的なベストプラクティス

このセクションのベストプラクティスは一般的なものであり、Internet Computer に特化したものではありません。このリストは決して完全なものではなく、過去に問題になった非常に具体的な懸念事項をいくつか挙げているに過ぎません。

=== フロントエンドで入力を検証する

==== セキュリティ上の懸念事項

信頼できない情報源（ユーザーなど）からのデータの入力検証を怠ると、不正なデータが保存され、ユーザーに配信される可能性があります。これは、DoS、インジェクション攻撃、フィッシングなどにつながる可能性があります。

==== 推奨

- Canister でのデータ検証に加え、フロントエンドでデータ検証を実施しましょう。データ検証はできるだけ早く行うべきです。
- link:https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html#goals-of-input-validation[OWASP Input Validation Cheat Sheet] を御覧ください。

[[dont-load-untrusted-content]]
=== 信頼できないドメインから JavaScript（およびその他のアセット）を読み込まない

==== セキュリティ上の懸念事項

`<canister-id>.ic0.app` 以外のドメインから信頼されていない JavaScript を読み込むことは、そのドメインを完全に信頼することを意味します。また、これらのドメイン（`<canister-id>.raw.ic0.app` を含む）から読み込まれたアセットはアセット認証を使用しません。

もし、悪意のある JavaScript を配信した場合、LocalStorage から agent-js が管理する秘密鍵を読み取るなどして、Web アプリまたはアカウントを乗っ取ることができます。

信頼できないドメインから CSS などの他のアセットを読み込むことは、セキュリティリスクであることに注意してください。例えば、link:https://xsleaks.dev/docs/attacks/css-injection/[ここ] を参照してください。

==== 推奨

- JavaScript やその他のアセットを他のオリジンから読み込むことは避けるべきです。特にセキュリティ上重要なアプリケーションでは、他のドメインが信頼できるものであると仮定することはできません。
- ブラウザに配信されるすべてのコンテンツが、Canister によって提供され、アセット証明書を使用して証明されていることを確認します。これは、特に JavaScript、フォント、CSS などに対して当てはまります。
- link:https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[コンテンツセキュリティポリシー] を使用して、他のオリジンからのスクリプトやその他のコンテンツがまったく読み込まれないようにします。link:web-app-development-security-best-practices#define-security-headers[コンテンツセキュリティポリシー（CSP）を含むセキュリティヘッダを定義する] も参照してください。

[[define-security-headers]]
=== コンテンツセキュリティポリシー（CSP）を含むセキュリティヘッダを定義する

==== セキュリティ上の懸念事項

セキュリティヘッダは多くのセキュリティに関する問題の対応に使用されます。例えば、link:https://owasp.org/www-community/attacks/Clickjacking[クリックジャッキング]からの防御、link:https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html[TLS]の強制、link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src[信頼できないドメインからの JavaScript または他のコンテンツがブラウザで実行しない]ようにするなどです。これらのヘッダーを適切に設定しないと、明確なセキュリティ上の問題が発生し、多層防御が失われます。

==== 推奨

- link:https://securityheaders.com/[https://securityheaders.com/] を使用してサイトをチェックします。
- link:https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html[HSTS]、link:https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[CSP]、link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options[X-Frame-Options]、link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy[Referrer-Policy]、Permissions-Policy (link:https://www.permissionspolicy.com/[generator]) を使用します。
- これらのヘッダ（CSP を含む）は、例えば link:https://github.com/dfinity/internet-identity[internet identity] で正常に統合されています。
- CSPを link:https://csp-evaluator.withgoogle.com/[CSP evaluator] に照らしてチェックしてください。
- link:https://owasp.org/www-project-secure-headers/[OWASP secure headers project] も参照してください。

=== 暗号化：Web Crypto API を使って XSS からキーマテリアルを保護する

==== セキュリティ上の懸念事項

ブラウザのストレージ （link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[sessionStorage] や link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[localStorage] など）に鍵を保存することは、これらの鍵に JavaScript コードがアクセスできるため、安全でないと考えられています。これは、XSS 攻撃や、他のドメインから信頼できないスクリプトを読み込むときに起こる可能性があります（ link:web-app-development-security-best-practices#dont-load-untrusted-content[信頼できないドメインから JavaScript（およびその他のアセット）を読み込まない] も参照して下さい）。

==== 推奨

link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API[WebCrypto API] を使用して、JavaScript からキーマテリアルを隠します。`generateKey` で `extractable=false` を使用します。link:https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey[これ] を参照してください。この例は、People Parties プロジェクトで見ることができます。link:https://github.com/dfinity/people-parties/blob/06208183a2679189d02bc5e64dcbd71c5f5dfbed/frontend/src/services/auth.ts#L111-L120[ここ] を参照してください。これにより、JavaScript から秘密鍵にアクセスすることは不可能になります。

=== 安全な Web フレームワークを使用する

==== セキュリティ上の懸念事項

最近の Web フレームワークは、Web ページに表示される潜在的なユーザー提供のデータを安全にエスケープ／サニタイズするため、XSS のような攻撃を非常に難しくしています。このようなフレームワークを使用しないことは、XSS のような攻撃を回避することが困難であるため危険です。

==== 推奨

- XSS を回避するために、link:https://github.com/dfinity/nns-dapplink:https://svelte.dev/[Svelte] のような安全なテンプレート機構を持つ Web フレームワークを使用してください。これは、例えば、[NNS Dapp] プロジェクトで使用されています。
- link:https://svelte.dev/docs#template-syntax-html[@html in Svelte] のような安全でない機能のフレームワークは使わないでください。

=== ログアウトが有効であることを確認する

==== セキュリティ上の懸念事項

ユーザーによるログアウト操作が有効でない場合、例えば、共有または公共のデバイスが使用されている場合、アカウントの乗っ取りにつながる可能性があります。

==== 推奨

- ログアウト時にすべてのセッションデータ（特に link:https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage[sessionStorage] と link:https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage[localStorage] ）、link:https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API[IndexedDB] などをクリアしてください。
- あるタブでログアウトが発生した場合、同じオリジンを表示している他のブラウザタブもログアウトされることを確認してください。これは、agent-js が初期化されると秘密鍵をメモリに保持するため、agent-js を使用する場合は自動的に起こりません。

=== プロンプトを使用してセキュリティ上重要な操作についてユーザーに警告しユーザーに明示的に確認させる

==== セキュリティ上の懸念事項

そうでない場合、ユーザーは誤って機密性の高いアクションを実行する可能性があります。

==== 推奨

- アクションの正確な結果を説明するセキュリティ警告を含むプロンプトをユーザーに表示し、明示的に確認させます。
- 例えば、WebAuthn デバイスを使用して、ユーザーに特定の重要なアクションやトランザクションを確認させることです。これは例えば、トークンや Cycle の転送が含まれる場合に推奨されます。例えば、link:https://github.com/dfinity/nns-dapp[NNS Dapp] でハードウェアウォレットを使用すると、これが実現されます。



////
= Web App Development Security Best Practices

== Authentication

=== Use a well-audited authentication service and client side IC libraries

==== Security Concern

Implementing user authentication and canister calls yourself in your web app is error prone and risky. For example, if canister calls are implemented from scratch, there may be bugs around signature creation or verification.

==== Recommendation

- Consider using e.g. link:https://github.com/dfinity/internet-identity[Internet Identity] for authentication, use link:https://github.com/dfinity/agent-js[agent-js] for making canister calls, and the link:https://github.com/dfinity/agent-js/tree/main/packages/auth-client[auth-client] for interacting with internet identity from your dApp.
- It is of course also an option to consider alternative authentication frameworks on the IC for authentication.

=== Set an appropriate session timeout

==== Security Concern

Currently, Internet Identity issues delegations with an expiry time. This expiry time can be set in the link:https://github.com/dfinity/agent-js/tree/main/packages/auth-client[auth-client]. After a delegation expires, the user has to re-authenticate. Setting a good value is a trade-off between security and usability.

==== Recommendation

See the link:https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-expiration[OWASP Recommendations]. A timeout of 30min should be set for security sensitive applications.

Note: Idle timeouts might be introduced soon, see link:https://forum.dfinity.org/t/authclient-update-idle-timeouts/10464[this].

=== Don’t use fetchRootKey in agent-js in production

==== Security Concern

`agent.fetchRootKey()` can be used in link:https://github.com/dfinity/agent-js[agent-js] to fetch the root subnet threshold public key from a status call in test environments. This key is used to verify threshold signatures on certified data received through canister update calls. Using this method in a production web app gives an attacker the option to supply their own public key, invalidating all authenticity guarantees of update responses.

==== Recommendation

Never use `agent.fetchRootKey()` in production builds, only in test builds. Not calling this method will result in the hard coded root subnet public key of mainnet being used for signature verification, which is the desired behavior in production.

== Nonspecific to the Internet Computer

The best practices in this section are very general and not specific to the Internet Computer. This list is by no means complete and only lists a few very specific concerns that have led to issues in the past.

=== Validate input in the front-end

==== Security Concern

Missing input validation of data from untrusted sources (e.g. users) can lead to malformed data being persisted and delivered back to users. This may lead to DoS, injection attacks, phishing, etc.

==== Recommendation

- Perform data validation already in the front end, in addition to data validation in the canister. Data validation should happen as early as possible.
- See the link:https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html#goals-of-input-validation[OWASP Input Validation Cheat Sheet]

[[dont-load-untrusted-content]]
=== Don’t load JavaScript (and other assets) from untrusted domains

==== Security Concern

Loading untrusted JavaScript from domains other than `<canister-id>.ic0.app` means you completely trust that domain. Also, assets loaded from these domains (incl. `<canister-id>.raw.ic0.app`) will not use asset certification.

If they deliver malicious JavaScript they can take over the web app/account by e.g. reading the private key managed by agent-js from LocalStorage.

Note that also loading other assets such as CSS from untrusted domains is a security risk, see e.g. link:https://xsleaks.dev/docs/attacks/css-injection/[here].

==== Recommendation

- Loading JavaScript and other assets from other origins should be avoided. Especially for security critical applications, we can't assume other domains to be trustworthy.
- Make sure all the content delivered to the browser is served and certified by the canister using asset certification. This holds in particular for any JavaScript, but also for fonts, CSS, etc.
- Use a link:https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[Content Security Policy] to prevent scripts and other content from other origins to be loaded at all. See also link:web-app-development-security-best-practices#define-security-headers[Define security headers including a Content Security Policy (CSP)].

[[define-security-headers]]
=== Define security headers including a Content Security Policy (CSP)

==== Security Concern

Security headers can be used to cover many security concerns, e.g. disallow link:https://owasp.org/www-community/attacks/Clickjacking[clickjacking], link:https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html[harden TLS], make sure link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src[JavaScript or other content from untrusted domains cannot be executed in the browser], etc. Not configuring these headers appropriately can lead to concrete security issues and missing defense-in-depth.

==== Recommendation

- Check your site using link:https://securityheaders.com/[https://securityheaders.com/]
- Use link:https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html[HSTS], link:https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[CSP], link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options[X-Frame-Options], link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy[Referrer-Policy], Permissions-Policy (link:https://www.permissionspolicy.com/[generator])
- These headers (including CSP) have been successfully integrated e.g. in link:https://github.com/dfinity/internet-identity[internet identity].
- Check your CSP against link:https://csp-evaluator.withgoogle.com/[CSP evaluator]
- See also the link:https://owasp.org/www-project-secure-headers/[OWASP secure headers project]

=== Crypto: Protect key material against XSS using Web Crypto API

==== Security Concern

Storing key material in browser storage (such as link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[sessionStorage] or link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[localStorage]) is considered unsafe because these keys can be accessed by JavaScript code. This could happen through an XSS attack or when loading untrusted scripts from other domains (see also link:web-app-development-security-best-practices#dont-load-untrusted-content[Don’t load JavaScript from untrusted domains].

==== Recommendation

Use link:https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API[WebCrypto API] to hide key material from JavaScript, by using `extractable=false` in `generateKey` , see link:https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey[this]. An example for this can be found in the people parties project, see link:https://github.com/dfinity/people-parties/blob/06208183a2679189d02bc5e64dcbd71c5f5dfbed/frontend/src/services/auth.ts#L111-L120[here]. This makes it impossible to access the private key from JavaScript.

=== Use a secure web framework

==== Security Concern

Modern web frameworks make attacks such as XSS very difficult since they safely escape / sanitize any potentially user-provided data that is rendered on a web page. Not using such a framework is risky as it is hard to avoid attacks like XSS.

==== Recommendation

- Use a web framework that has a secure templating mechanism such as link:https://github.com/dfinity/nns-dapplink:https://svelte.dev/[Svelte] to avoid XSS. This is used e.g. in the [NNS dApp] projects.
- Don’t use insecure features of the framework, such as e.g. link:https://svelte.dev/docs#template-syntax-html[@html in Svelte].

=== Make sure the logout is effective

==== Security Concern

If a logout action by a user is not effective, this may lead to account takeover e.g. if a shared or public device is used.

==== Recommendation

- Clear all session data (especially link:https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage[sessionStorage] and link:https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage[localStorage]), clear link:https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API[IndexedDB], etc. on logout.
- Make sure also other browser tabs showing the same origin are logged out if the logout is triggered in one tab. This does not happen automatically when agent-js is used, since agent-js keeps the private key in memory once initialized.

=== Use prompts to warn the user on any security critical actions, let the user explicitly confirm

==== Security Concern

If this is not the case, a user may by accident execute some sensitive actions.

==== Recommendation

- Show the user a prompt with a security warning describing the exact consequences of the action and let them confirm explicitly.
- For applications with high security requirements, consider the use of transaction approval, i.e. using e.g. a WebAuthn device to let the user confirm certain critical actions or transactions. This is recommended e.g. when token or cycle transfers is involved. For example, using a hardware wallet in the link:https://github.com/dfinity/nns-dapp[NNS dApp] achieves this.



////
