= デジタルアセットのセルフカストディを選択する
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

セルフカストディとは、トークン配布のオプションの一つで、第三者が代行することなく、自分のデジタルアセットと秘密鍵の管理に対して唯一の責任を持つことを可能にするものです。

デジタルアセットを自分で管理することを選択した場合、さまざまな種類の *セルフカストディ・ソリューション* があり、それらのソリューションはセキュリティや使いやすさが異なることを認識する必要があります。
特定のセルフカストディ・ソリューションを決定する前に、利用可能なさまざまなオプションとその違いについて、時間をかけて学習する必要があります。

このガイドでは、カストディ戦略の一環としての *コールドストレージ* の概念と、現在利用できる最も一般的なコールドストレージの種類を簡単に紹介します。

コールドストレージやその他の保管方法についての詳しい情報は、ご自身で調べ、その影響を十分に理解した上で進める必要があります。

== コールドストレージ

コールドストレージとは、インターネットに接続されていないオフラインのデバイスに秘密鍵を保存しておくことを意味します。
コールドストレージはソフトウェアのセキュリティ侵害やコールドストレージソリューションの紛失・盗難が発生した場合に、鍵の漏洩を防ぐことができるため、デジタルアセットのセルフカストディとして人気のあるソリューションです。

コールドストレージのアプローチと秘密鍵を保護するためのベストプラクティスの詳細については、以下の追加資料を参照してください：

* link:https://www.investopedia.com/terms/c/cold-storage.asp[コールドストレージ]

* link:https://www.ledger.com/academy/hardwarewallet/best-practices-when-using-a-hardware-wallet#:~:text=%E2%80%93%20Keep%20your%20Recovery%20sheet%20physically,or%20smartphone%20screen%20with%20caution[ハードウェアウォレット利用する際のベストプラクティス]

* link:https://blog.trailofbits.com/2018/11/27/10-rules-for-the-secure-use-of-cryptocurrency-hardware-wallets/[暗号通貨ハードウェアウォレットを安全に利用するための10ヶ条]

== 一般的なコールドストレージのオプション

一般的なコールドストレージの種類は以下の通りです：

* <<Hardware wallets, ハードウェアウォレット>>
* <<Air-gapped computers, エアギャップコンピューター>>
* <<Paper wallets, ペーパーウォレット>>

=== ハードウェアウォレット

*ハードウェアウォレット* は、あなたのデジタルアセットを保持する物理デバイスです。
秘密鍵は、インターネットに接触しないデバイスの安全な部分に保管されます。
物理デバイスに分割して保存することで、インターネットに接続されたデバイスにつきもののリスクを軽減することができます。
しかし、物理デバイスに依存しているため、デバイスを失うことは、デジタルアセットへのアクセスを失うことでもあるのです。

ハードウェアウォレットに保存されたアセットは、秘密のシードフレーズを使用して保護されているため、ほとんどの場合、ハードウェアウォレットの紛失から回復することができます。
このシードフレーズをコピーして、例えば <<Paper wallets, ペーパーウォレット>> という形で保存しておけば、新しいデバイスをシードフレーズで初期化し、デジタルアセットへのアクセスを回復することができます。

詳しい情報はこちらから：
link:https://cointelegraph.com/explained/crypto-wallets-explained[クリプトウォレットの説明]

=== エアギャップコンピューター

*エアギャップコンピューター* は、インターネットと相互作用する安全でないネットワークや、家庭内の安全でないローカルエリア・ネットワークから隔離されています。

標準的なパソコンなどをエアギャップコンピューターに変換するには、ネットワークカードを物理的に取り外す、特定のソフトウェアを無効にする、あるいはインターネットに接続する前にマシンを完全に消去するなどの準備が必要になる場合があります。

エアギャップコンピューターの安全性をどの程度確保したいかに依りますが、デジタルアセットを収集するための最小限のオペレーティング・システムを提供するブートイメージを使用し、そのプロセスで発生した痕跡をすべて取り除き、すべての取引の完了後にコンピュータを通常通りに再起動するという方法があります。
詳しくは、link:https://www.wired.com/story/extreme-security-measures/[心配性のためのセキュリティ対策] および 
link:https://www.howtogeek.com/687792the-ultimate-defense-what-is-an-air-gapped-computer/[究極の防御：エアギャップコンピューターとは] をご覧ください。

=== ペーパーウォレット

*ペーパーウォレット* とは、お客様の重要な鍵情報（場合によってはQRコードも）を印刷した紙で、デジタルアセットの取引を円滑に行うために使用されるものです。
ペーパーウォレットは劣化しやすく、安全性に欠けたり、簡単に紛失や盗難に遭う可能性があるため、推奨されないことが多いです。

ただし、ハードウェアウォレットのバックアップとして、ペーパーウォレットを作成し、貸金庫などの安全な場所に保管するのはいかがでしょうか。

詳しくは、link:https://blockgeeks.com/guides/paper-wallet-guide/#Paper_wallets[ペーパーウォレット] をご覧ください。

== アセットの安全性確保

コールドストレージやカストディのソリューションを調査するのは、最終的にはお客様の責任です。

どのようなセルフカストディ・ソリューションを選択するかにかかわらず、デジタルアセットを安全に保管することは、お客様の責任でもあります。

このことを念頭に置いて、以下の一般的な推奨事項に留意してください。

* デジタルアセット・ストレージ・ソリューションの設定に、仕事用のコンピューターを使わないでください。
特に、そのコンピューターが日常的にインターネットに接続されている場合、個人情報が失われたり、危険にさらされる可能性があります。

* コールドストレージのウォレットや個人情報を、漏洩する可能性のある公共の場所に放置しないでください。

* 秘密鍵やシードフレーズを紛失しないでください。紛失した場合、デジタルアセットに永久にアクセスできなくなります。



////
= Choosing self-custody for digital assets
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Self-custody is a token distribution option that enables you to have sole responsibility over your digital assets and over the management of your private keys, without the need of a third party to act on your behalf. 

If you have made the choice to control your digital assets yourself, you should be aware that there are different kinds of *self-custody solutions* and that those solutions vary in their security and ease of use. 
Before you decide on a specific self-custody solution, you should spend some time learning about the various options available and how they differ. 

This guide provides a brief introduction to the concept of *cold storage* as part of your custody strategy and the most common types of cold storage currently available. 

For additional information about cold storage and other custody options, you should do your own research and be sure that you understand the ramifications of your choices thoroughly before proceeding.

== Cold storage

Cold storage means that you are keeping private keys stored offline in a device that is not connected to the internet. 
Cold storage is a popular solution for self-custody of digital assets because it makes it more difficult for your keys to be compromised if there is a software security breach or if your cold storage solution is lost or stolen.

For more information about approaches to cold storage and best practices for securing your private keys, see the following additional resources:

* link:https://www.investopedia.com/terms/c/cold-storage.asp[Cold storage]

* link:https://www.ledger.com/academy/hardwarewallet/best-practices-when-using-a-hardware-wallet#:~:text=%E2%80%93%20Keep%20your%20Recovery%20sheet%20physically,or%20smartphone%20screen%20with%20caution[Best Practices when using a Hardware Wallet]

* link:https://blog.trailofbits.com/2018/11/27/10-rules-for-the-secure-use-of-cryptocurrency-hardware-wallets/[10 Rules for the Secure Use of Cryptocurrency Hardware Wallets]

== Common cold storage options

The most common types of cold storage include the following:

* <<Hardware wallets>>
* <<Air-gapped computers>>
* <<Paper wallets>>

=== Hardware wallets

A *hardware wallet* is a physical device that holds your digital assets. 
Private keys are stored in a secure part of the device that does not come into contact with the internet. 
The partitioned storage on the physical device reduces the risks that are associated with devices connected to the internet. 
Because you are relying on a physical device, however, losing the device also means losing access to your digital assets.

In most cases, you can recover from the loss of a hardware wallet because the assets stored on hardware wallets are secured using a secret seed phrase.
. If you copy and secure the seed phrase—for example, by storing it in the form of a <<Paper wallets,paper wallet>>—you can initialize a new device with the seed phrase and regain access to your digital assets.

For more information, see
link:https://cointelegraph.com/explained/crypto-wallets-explained[Crypto Wallets, Explained].

=== Air-gapped computers

An *air-gapped computer* is isolated from insecure networks that interact with the internet or unsecured local area networks in your home.

Converting a standard personal computer or similar device into an air-gapped computer might require you to physically remove network cards, disable certain software, or be prepared to completely wipe the machine before connecting it to the internet again.

Depending on how secure you want your air-gapped computer to be, one option is to use a bootable image that provides a minimal operating system to collect your digital assets then remove any artifacts from that process and reboot the computer normally after completing any transaction.
For more information, see link:https://www.wired.com/story/extreme-security-measures/[Extreme Security Measures for the Extra Paranoid] and 
link:https://www.howtogeek.com/687792the-ultimate-defense-what-is-an-air-gapped-computer/[The Ultimate Defense: What Is an Air Gapped Computer?].

=== Paper wallets

A *paper wallet* is a piece of printed paper that contains your important key information (in some cases, even a QR code) and is used for facilitating digital asset transactions. 
Paper wallets are often not recommended because they are susceptible to degradation and could be insecure or lost or stolen easily.

As a backup to a hardware wallet, however, you might want to create a paper wallet and store it in a secure location such as a safe deposit box.

For more information, see link:https://blockgeeks.com/guides/paper-wallet-guide/#Paper_wallets[Paper wallets].

== Keeping assets safe

It is ultimately your responsibility to research the cold storage and custody solutions available to you.

Regardless of the type of self-custody solution you select, it is also your responsibility to keep your digital assets safe.

With this in mind, you should take note of the following general recommendations:

* Do not use a work computer to configure a digital asset storage solution. Your private personal data could be lost or 
compromised while hosted on a work computer, especially if that computer is routinely connected to the internet. 

* Do not leave your cold storage wallet or any private information in a public place where it could be compromised.

* Do not lose your private key or your seed phrase. If lost, you will be permanently unable to access your digital assets.



////