= セルフカストディのクイックスタート
:description: How you can use your ICP tokens.
:keywords: Internet Computer,blockchain,cryptocurrency,ICP tokens,smart contracts,cycles,wallet,software canister,developer onboarding
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Internet Computer のエコシステム内では、Internet Computer プロトコル・トークン（ICP トークン）はネイティブ・ユーティリティ・トークンです。
ICP トークンは、{IC} のガバナンスとエコノミクスの両方において重要な役割を担っています。

この _セルフカストディのクイックスタート_ のシナリオは、以下を想定しています：

* あなたは新しい ICP トークン所有者である。
* あなたは ICP トークンで何ができるかを理解したい。
* {sdk-short-name} コマンドラインインターフェース DFX を使用して、ICP トークンを変換、転送、ロックする方法を知りたい。

まだトークン保有者でない方は、ICP トークンを取引所から購入するか、トークン付与を受けてからカストディを行う必要があります。ICP トークンの入手方法とカストディオプションの概要については、link:../developers-guide/concepts/tokens-cycles{outfilesuffix}#get-cycles[ICPトークンの入手方法] とlink:custody-options-intro{outfilesuffix}[デジタルアセットのセルフカストディを選択する] を参照して下さい。

他のアプリケーション link:https://nns.ic0.app[Network Nervous System（NNS）アプリケーション] やハードウェアウォレットが提供するユーザーインターフェイスなどを使用して ICP トークンとやり取りする場合は、そのアプリケーションのドキュメントを参照してください。

この _セルフカストディ クイックスタート_ は、{sdk-short-name} コマンドラインインターフェース DFX を使用した ICP トークンとの対話にのみ焦点を当てています。

== ICP トークンの使用方法

次の図はトークンの最も一般的な3つの使用方法の概要を簡略化したものです。

image:developers-guide:icp-tokens-how-to-use.svg[]

この図が示すように、ICP トークンの使用方法は、主にそれを取得する際の目標によって異なります。

あなたが **開発者** または **起業家** である場合、ICP トークンは **Cycle** に変換することができます。Cycle は、製品やサービスを市場に提供するためのアプリケーションを構築し、デプロイするために使用することができます。

**ガバナンスへの参加** や {IC} の方向性に影響を与えることに関心のあるコミュニティのメンバーであれば、ICP トークンを Neuron と呼ばれるステークにロックして、プロポーザルの提出や投票ができるようにすることが可能です。

[[self-before]]
== 始める前に

はじめに、以下を確認します：

* インターネットに接続し、ローカルの **Intel-based macOS** または **Linux** コンピュータ上のシェル端末にアクセスできること。

* ローカルコンピュータで新しいターミナルシェルを開く方法と、ターミナルで基本的なコマンドライン・プログラムを実行する方法を知っていること。

* ICP トークンをセルフカストディウォレットに保管していること。

* ローカルコンピュータのターミナルで次のコマンドを実行して、{sdk-long-name} をダウンロードおよびインストールすること：
+
[source,bash]
----
sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
----

* セルフカストディに使用する Identity の公開鍵・秘密鍵のバックアップコピーを作成したこと。
+
例えば、{sdk-long-name} `+dfx+` コマンドラインインターフェイスを使用して作成したデフォルトの開発者用 Identity を使用している場合、安全な場所に `+~/.config/dfx/identity/default/identity.pem+` ファイルをバックアップしておく必要があります。

* ICP トークンを含む操作を実行するための安全な環境があること。
+
セキュリティのベストプラクティスとして、ICP トークンの授受を伴う作業には、最小限のハードウェアとソフトウェアを備えたエアギャップ付きのコンピューターと、ネットワークに接続されたコンピューターの両方が必要になります。
実際には、2台のコンピュータ間でファイルを移動させるなど、リスクを最小限に抑えるための工夫が必要です。
+
この _{doctitle}_ では、わかりやすくするために、ネットワークに接続された1台のコンピュータを使って、主要なタスクを完了する方法を説明します。

== 台帳に接続し、アカウント ID を取得する

ICP トークンの取引はすべて、Internet Computer 上で動作する台帳 Canister に記録されます。
この説明では、`+dfx+` が作成した `+default+` 開発者 Identity を使用することを想定しています。

この Identity は *principal* データ型で表され、 *principal ID* と呼ばれていたりします。
この Identity の表現は、Bitcoin や Ethereum のアドレスに似ています。

しかし、開発者 Identity に関連付けられた Principal は、通常、台帳上の *Account ID* と同じではありません。Principal 識別子と Account 識別子は関連しておりどちらもあなたの Identity をテキストで表現していますが、異なるフォーマットを使用しています。

台帳に接続してアカウント情報を取得するには、次のようにします：

. 以下のコマンドを実行し、カレントディレクトリに空の `+dfx.json+` ファイルを作成します：
+
[source,bash]
----
echo '{}' > dfx.json
----
. 次のコマンドを実行して、{IC} ネットワークの現在のステートと接続できることを確認します。
+
[source,bash]
----
dfx ping ic
----
+
以下のような出力が表示されるはずです：
+
....
{
  "ic_api_version": "0.18.0"  "impl_hash": "d639545e0f38e075ad240fd4ec45d4eeeb11e1f67a52cdd449cd664d825e7fec"  "impl_version": "8dc1a28b4fb9605558c03121811c9af9701a6142"  "replica_health_status": "healthy"  "root_key": [48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 129, 76, 14, 110, 199, 31, 171, 88, 59, 8, 189, 129, 55, 60, 37, 92, 60, 55, 27, 46, 132, 134, 60, 152, 164, 241, 224, 139, 116, 35, 93, 20, 251, 93, 156, 12, 213, 70, 217, 104, 95, 145, 58, 12, 11, 44, 197, 52, 21, 131, 191, 75, 67, 146, 228, 103, 219, 150, 214, 91, 155, 180, 203, 113, 113, 18, 248, 71, 46, 13, 90, 77, 20, 80, 95, 253, 116, 132, 176, 18, 145, 9, 28, 95, 135, 185, 136, 131, 70, 63, 152, 9, 26, 11, 170, 174]
}
....
. （オプション） 以下のコマンドを実行して、現在使用している開発者 Identity を確認します：
+
[source,bash]
----
dfx identity whoami
----
+
ほとんどの場合、現在 `+default+` の開発者 Identity を使用していることが確認できるはずです。たとえば：
+
....
default
....
. （オプション）次のコマンドを実行して、現在の Identity の Principal のテキスト表現を表示します：
+
[source,bash]
----
dfx identity get-principal
----
+
このコマンドは、次のような出力を表示します：
+
....
tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
....
. 以下のコマンドを実行し、開発者 Indentity のAccount ID を取得します：
+
[source,bash]
----
dfx ledger account-id
----
+
このコマンドは、開発者 Identity に関連付けられた台帳 Accout IDを表示します。
たとえば、次のような出力が表示されるはずです：
+
....
03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
....
. 以下のコマンドを実行して、アカウントの残高を確認します：
+
[source,bash]
----
dfx ledger --network ic balance
----
このコマンドは、台帳アカウントから ICP トークンの残高を表示します。
例えば、次のような出力が表示されるはずです：
+
....
10.00000000 ICP
....

[[convert-icp]]
== ICPトークンを Cycle に変換する

ICP トークンを台帳アカウントで使用してアプリケーション開発の動力（ガス）としたい場合、まずトークンを Cycle に変換し、Cycle ウォレットとなる Canister に Cycle を転送する必要があります。

ICP トークンを Cycle に変換するには：

. 以下のようなコマンドを実行して、台帳アカウントから ICP トークンを転送し、Cycle を持つ新しい Canister を作成します：
+
[source,bash]
----
dfx ledger --network ic create-canister <controller-principal-identifier> --amount <icp-tokens> 
----
+
このコマンドは、`+--amount+` 引数に指定した ICP トークンの数を Cycle に変換し、Cycle を指定した Principal で制御される新しい Canister ID に関連付けます。
+
例えば、次のコマンドは 1.25 ICP トークンを Cycle に変換し、新しい Canister のコントローラーとしてdefault のPrincipal ID を指定します。
+
....
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --amount 1.25 
....
+
取引が成功した場合、台帳にはそのイベントが記録され、以下のような出力が表示されます：
+
....
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
....
. 以下のようなコマンドを実行して、新しく作成した Canister プレースホルダーに Cycle ウォレットコードをインストールします：
+
[source,bash]
----
dfx identity --network ic deploy-wallet <canister-identifer>
----
+
たとえば：
+
....
dfx identity --network ic deploy-wallet 53zcu-tiaaa-aaaaa-qaaba-cai
....
+
このコマンドは、次のような出力を表示します：
+
....
Creating a wallet canister on the ic network.
The wallet canister on the "ic" network for user "default" is "53zcu-tiaaa-aaaaa-qaaba-cai"
....

== ICP トークンを他のアカウントに移動する

ICP トークンを台帳上の別のアカウントに転送したい場合は、転送先のアカウント ID を知っておく必要があります。

ICP トークンを別のアカウントに転送するには：

. 以下のコマンドを実行して、台帳アカウントを制御できる Identity を使用していることを確認します：
+
[source,bash]
----
dfx identity whoami
----
. 以下のコマンドを実行して、自分の Identity に関連する台帳アカウントの現在の残高を確認します：
+
[source,bash]
----
dfx ledger --network ic balance
----
 
. 以下のようなコマンドを実行して、ICP トークンを別のアカウントに転送します。
+
[source,bash]
----
dfx ledger --network ic transfer <destination-ledger-account-id> --icp <ICP-amount> --memo <numeric-memo>
----
+
たとえば：
+
....
dfx ledger --network ic transfer ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406 --icp 5 --memo 12345
....
+
この例では、`+--icp+` コマンドラインオプションで整数を使用して、指定したアカウントに ICP トークンを転送する方法を説明します。
+
--

* *e8s* と呼ばれる ICP トークンの端数は、 `+--e8s+` オプションを単独で、あるいは `+--icp+` オプションと組み合わせて指定することができます。

* また、`+--amount+` を使用すると、転送する ICP トークンの数を小数点以下8桁まで、例えば `+5.00000025+` のように指定することができます。
--

+
宛先アドレスは、{IC} ネットワーク上で動作する台帳 Canister のアドレス、link:https://nns.ic0.app[Network Nervous System アプリケーション] を使って追加したアカウント、取引所で持っているウォレットアドレスのいずれかを使用できます。
+
link:https://nns.ic0.app[Network Nervous System アプリケーション] のアカウントに ICP トークンを転送した場合、取引が反映されるまでにブラウザを更新する必要がある場合があります。
+
`+dfx ledger+` のコマンドラインオプションの使い方については、link:../developers-guide/cli-reference/dfx-ledger{outfilesuffix}[dfx ledger] を参照してください。

== ICP トークンを Neuron に張り付け、ロックする

ICP トークンをロックしてガバナンスに参加し、報酬を獲得したい場合は、link:https://nns.ic0.app[Network Nervous System (NNS) アプリケーション] または `+dfx canister call+` コマンドを使用する必要があります。

ICP トークンをロックしてステークされた Neuron を作成するのは、{sdk-short-name} コマンドラインインターフェイスを使用する場合、link:https://nns.ic0.app[Network Nervous System（NNS）アプリケーション] を使用する場合よりも複雑なので、このガイドにはその手順は含まれていません。

////

The first step, however, is to transfer some ICP tokens from your ledger account to the `+governance+` canister to create a neuron.
The following steps illustrate how you can do that.

To create a neuron from ICP tokens:

. Determine the target account by running a command similar to the following:
+
[source,bash]
----
dfx canister --network ic call governance build_stake_transfer_targets "(<unique-memo> : Nat64)"
----
+
For example:
+
....
dfx canister --network ic call governance build_stake_transfer_targets "(0001 : Nat64)"
....
+
This command uses the principal associated with your current identity and the value you specify for the _<unique_memo>_ field to return an account identifier and a sub-account for the transfer.
+
In the command output, you should see an account identifier that looks similar to the following:
+
....
ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406
....
You should also see a sub-account similar to the following:
+
....
\c1_\8d\22/_\08\db\89\0c0\c6\a7C}\b5\9d=3\b92]1\1fHT\c9t\af\99\ad\fb
....
. Transfer ICP tokens from the ledger account to the target account identifier returned in the previous step by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network ic transfer <destination-account-id> --amount <ICP-amount> --memo <unique-memo>
----
+
For example:
+
....
dfx ledger --network ic transfer ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406 --amount 20 --memo 0001
....
+
If the transfer is successful, the command returns the block height for the transaction.
For example:
+
....
Transfer sent at BlockHeight: 20
....

=== Configuring neuron properties

After the neuron is created, there are several properties that need to be configured to lock the stake, set the dissolve delay, and begin submitting proposals and earning rewards.
You can set these properties for a neuron from the command line by calling the `+governance+` canister and the `+manage_neuron+` method or by using the Network Nervous System application (nns.ic0.app).

For example, if you continue using the `+dfx+` command-line interface, you might configure a neuron to have a hot key by running a command similar to the following:

....
dfx canister --network ic governance manage_neuron \
"( record {id = opt record { id = <neuron_id>; \
command = opt variant { Configure = record { operation \
= opt variant {AddHotKey = record { new_hot_key = \
principal <new_hot_key_principal_id> }}}}}}"
....

=== Learning more about the Network Nervous System
////
Network Nervous System については、link:https://medium.com/dfinity/understanding-the-internet-computers-network-nervous-system-neurons-and-icp-utility-tokens-730dab65cae8[Understanding the {IC}'s Network Nervous System, Neurons, and ICP Utility Tokens] を参照してください。

Neuron のロック期間と溶解遅延の設定についての詳細は、link:https://medium.com/dfinity/getting-started-on-the-internet-computers-network-nervous-system-app-wallet-61ecf111ea11[Getting Started | {IC} Network Nervous System Application & Wallet] を参照してください。



////
= Self-custody quick start
:description: How you can use your ICP tokens.
:keywords: Internet Computer,blockchain,cryptocurrency,ICP tokens,smart contracts,cycles,wallet,software canister,developer onboarding
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Within the Internet Computer ecosystem, Internet Computer Protocol tokens (ICP tokens) are a native utility token.
ICP tokens play a key role in both the governance and economics of the {IC}. 

This _Self-Custody Quick Start_ scenario assumes:

* You are a new ICP token holder.
* You want to understand what you can do with your ICP tokens.
* You want to know how to convert, transfer, or lock your ICP tokens using the {sdk-short-name} command-line interface DFX.

If you aren't yet a token holder, you'll need to purchase ICP tokens from an exchange or receive a token grant before you can take custody. For an overview of how to get ICP tokens and custody options, see link:../developers-guide/concepts/tokens-cycles{outfilesuffix}#get-cycles[How you can get ICP tokens] and link:custody-options-intro{outfilesuffix}[Choosing self-custody for digital assets].

If you are using another application—such as the link:https://nns.ic0.app[Network Nervous System (NNS) application] or the user interface provided by a hardware wallet—to interact with your ICP tokens, you should refer to the documentation for that application.

This _Self-Custody Quick Start_ focuses solely on interacting with ICP tokens using the {sdk-short-name} command-line interface DFX.

== How you can use ICP tokens

The following diagram provides a simplified overview of the three most common ways you can use tokens.

image:developers-guide:icp-tokens-how-to-use.svg[]

As this diagram suggests, how you use ICP tokens depends primarily on your goals in acquiring them.

If you are a **developer** or **entrepreneur**, ICP tokens can be converted to **cycles**. Cycles can then be used to build and deploy applications to deliver products and services to the market.

If you are a member of the community interested in **participating in governance** and influencing the direction of the {IC}, you can lock up ICP tokens in a stake—called a neuron—so that you can submit and vote on proposals.

[[self-before]]
== Before you begin

To get started, verify the following:

* You have an internet connection and access to a shell terminal on your local **Intel-based macOS** or **Linux** computer.

* You know how to open a new terminal shell on your local computer and how to run basic command-line programs in the terminal.

* You hold ICP tokens in a self-custody wallet.

* You have downloaded and installed the {sdk-long-name} by running the following command in a terminal on your local computer:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
----

* You have created a backup copy of the public/private key for the identity you are using for self-custody.
+
For example, if you are using the default developer identity created using the {sdk-long-name} `+dfx+` command-line interface,
you should have a backup of the `+~/.config/dfx/identity/default/identity.pem+` file stored in a secure location.

* You have a secure environment in which to perform operations involving ICP tokens.
+
As a security best practice, any operations that involve the transfer of ICP tokens would require both an air-gapped computer with minimal hardware and software and a computer connected to the network. 
In practice, this requires moving files between two computers and taking other precautions to minimize risks.
+
For simplicity, this _{doctitle}_ describes how to complete key tasks using a single computer connected to the network.

== Connect to the ledger and get your account identifier

All ICP token transactions are recorded in a ledger canister running on the Internet Computer.
These instructions assume that you are using the `+default+` developer identity that `+dfx+` has created for you.

This identity is represented by a *principal* data type and a textual representation of the principal often referred to as your *principal identifier*.
This representation of your identity is similar to a Bitcoin or Ethereum address.

However, the principal associated with your developer identity is typically not the same as your *account identifier* in the ledger. The principal identifier and the account identifier are related—both provide a textual representation of your identity—but they use different formats.

To connect to the ledger and get account information:

. Create an empty `+dfx.json+` file in your current directory by running the following command:
+
[source,bash]
----
echo '{}' > dfx.json
----
. Check the current status of the {IC} network and your ability to connect to it by running the following command
+
[source,bash]
----
dfx ping ic
----
+
You should see output similar to the following:
+
....
{
  "ic_api_version": "0.18.0"  "impl_hash": "d639545e0f38e075ad240fd4ec45d4eeeb11e1f67a52cdd449cd664d825e7fec"  "impl_version": "8dc1a28b4fb9605558c03121811c9af9701a6142"  "replica_health_status": "healthy"  "root_key": [48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 129, 76, 14, 110, 199, 31, 171, 88, 59, 8, 189, 129, 55, 60, 37, 92, 60, 55, 27, 46, 132, 134, 60, 152, 164, 241, 224, 139, 116, 35, 93, 20, 251, 93, 156, 12, 213, 70, 217, 104, 95, 145, 58, 12, 11, 44, 197, 52, 21, 131, 191, 75, 67, 146, 228, 103, 219, 150, 214, 91, 155, 180, 203, 113, 113, 18, 248, 71, 46, 13, 90, 77, 20, 80, 95, 253, 116, 132, 176, 18, 145, 9, 28, 95, 135, 185, 136, 131, 70, 63, 152, 9, 26, 11, 170, 174]
}
....
. (Optional) Confirm the developer identity you are currently using by running the following command:
+
[source,bash]
----
dfx identity whoami
----
+
In most cases, you should see that you are currently using your `+default+` developer identity.
For example:
+
....
default
....
. (Optional) View the textual representation of the principal for your current identity by running the following command:
+
[source,bash]
----
dfx identity get-principal
----
+
This command displays output similar to the following:
+
....
tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
....
. Get the account identifier for your developer identity by running the following command:
+
[source,bash]
----
dfx ledger account-id
----
+
This command displays the ledger account identifier associated with your developer identity.
For example, you should see output similar to the following:
+
....
03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
....
. Check your account balance by running the following command:
+
[source,bash]
----
dfx ledger --network ic balance
----
This command displays the ICP token balance from the ledger account.
For example, you should see output similar to the following:
+
....
10.00000000 ICP
....

[[convert-icp]]
== Convert ICP tokens to cycles

If you want to use your ICP tokens in your ledger account to power application development, you first must convert them to cycles and transfer the cycles to a canister that will be your cycles wallet.

To convert ICP tokens to cycles:

. Create a new canister with cycles by transferring ICP tokens from your ledger account by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network ic create-canister <controller-principal-identifier> --amount <icp-tokens> 
----
+
This command converts the number of ICP tokens you specify for the `+--amount+` argument into cycles, and associates the cycles with a new canister identifier controlled by the principal you specify.
+
For example, the following command converts 1.25 ICP tokens into cycles and specifies the principal identifier for the default identity as the controller of the new canister:
+
....
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --amount 1.25 
....
+
If the transaction is successful, the ledger records the event and you should see output similar to the following:
+
....
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
....
. Install the cycles wallet code in the newly-created canister placeholder by running a command similar to the following:
+
[source,bash]
----
dfx identity --network ic deploy-wallet <canister-identifer>
----
+
For example:
+
....
dfx identity --network ic deploy-wallet 53zcu-tiaaa-aaaaa-qaaba-cai
....
+
This command displays output similar to the following:
+
....
Creating a wallet canister on the ic network.
The wallet canister on the "ic" network for user "default" is "53zcu-tiaaa-aaaaa-qaaba-cai"
....

== Transfer ICP tokens to another account

If you want to transfer ICP tokens to another account in the ledger, you need to know the account identifier for the destination account.

To transfer ICP tokens to another account:

. Check that you are using an identity with control over the ledger account by running the following command:
+
[source,bash]
----
dfx identity whoami
----
. Check the current balance in the ledger account associated with your identity by running the following command:
+
[source,bash]
----
dfx ledger --network ic balance
----
 
. Transfer ICP tokens to another account by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network ic transfer <destination-ledger-account-id> --icp <ICP-amount> --memo <numeric-memo>
----
+
For example: 
+
....
dfx ledger --network ic transfer ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406 --icp 5 --memo 12345
....
+
This example illustrates how to transfer ICP tokens to the specified account using a whole number with the `+--icp+` command-line option.
+
--

* You can also specify fractional units of ICP tokens—called *e8s*—using the `+--e8s+` option, either on its own or in conjunction with the `+--icp+` option.

* Alternatively, you can use the `+--amount+` to  specify the number of ICP tokens to transfer with fractional units up to 8 decimal places, for example, as `+5.00000025+`.
--

+
The destination address can be an address in the ledger canister running on the {IC} network, an account you have added using the link:https://nns.ic0.app[Network Nervous System application], or the address for a wallet you have on an exchange.
+
If you transfer the ICP tokens to an account in the link:https://nns.ic0.app[Network Nervous System application], you might need to refresh the browser to see the transaction reflected.
+
For more information about using the `+dfx ledger+` command-line options, see link:../developers-guide/cli-reference/dfx-ledger{outfilesuffix}[dfx ledger].

== Lock ICP tokens by staking them in a neuron

If you want to lock up ICP tokens to participate in governance and earn rewards, you must use the link:https://nns.ic0.app[Network Nervous System (NNS) application] or `+dfx canister call+` commands.

Because locking up ICP tokens to create staked neurons is a more complex process when using the {sdk-short-name} command-line interface than it is when using the link:https://nns.ic0.app[Network Nervous System (NNS) application], the steps aren't included in this guide.

////
////

The first step, however, is to transfer some ICP tokens from your ledger account to the `+governance+` canister to create a neuron.
The following steps illustrate how you can do that.

To create a neuron from ICP tokens:

. Determine the target account by running a command similar to the following:
+
[source,bash]
----
dfx canister --network ic call governance build_stake_transfer_targets "(<unique-memo> : Nat64)"
----
+
For example:
+
....
dfx canister --network ic call governance build_stake_transfer_targets "(0001 : Nat64)"
....
+
This command uses the principal associated with your current identity and the value you specify for the _<unique_memo>_ field to return an account identifier and a sub-account for the transfer.
+
In the command output, you should see an account identifier that looks similar to the following:
+
....
ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406
....
You should also see a sub-account similar to the following:
+
....
\c1_\8d\22/_\08\db\89\0c0\c6\a7C}\b5\9d=3\b92]1\1fHT\c9t\af\99\ad\fb
....
. Transfer ICP tokens from the ledger account to the target account identifier returned in the previous step by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network ic transfer <destination-account-id> --amount <ICP-amount> --memo <unique-memo>
----
+
For example:
+
....
dfx ledger --network ic transfer ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406 --amount 20 --memo 0001
....
+
If the transfer is successful, the command returns the block height for the transaction.
For example:
+
....
Transfer sent at BlockHeight: 20
....

=== Configuring neuron properties

After the neuron is created, there are several properties that need to be configured to lock the stake, set the dissolve delay, and begin submitting proposals and earning rewards.
You can set these properties for a neuron from the command line by calling the `+governance+` canister and the `+manage_neuron+` method or by using the Network Nervous System application (nns.ic0.app).

For example, if you continue using the `+dfx+` command-line interface, you might configure a neuron to have a hot key by running a command similar to the following:

....
dfx canister --network ic governance manage_neuron \
"( record {id = opt record { id = <neuron_id>; \
command = opt variant { Configure = record { operation \
= opt variant {AddHotKey = record { new_hot_key = \
principal <new_hot_key_principal_id> }}}}}}"
....

=== Learning more about the Network Nervous System
////
////
For information about the Network Nervous System, see link:https://medium.com/dfinity/understanding-the-internet-computers-network-nervous-system-neurons-and-icp-utility-tokens-730dab65cae8[Understanding the {IC}'s Network Nervous System, Neurons, and ICP Utility Tokens].

For additional details about setting the locked period and dissolve delay for a neuron, see link:https://medium.com/dfinity/getting-started-on-the-internet-computers-network-nervous-system-app-wallet-61ecf111ea11[Getting Started | The {IC} Network Nervous System Application & Wallet]



////
