= dfx ping

`+dfx ping+` コマンドを使用すると、{platform} やテストネットへの接続を確認することができます。
このコマンドではデプロイ先の環境に接続できるかどうかを確認することができます。

このコマンドはプロジェクトのディレクトリ構造内からしか実行できないことに注意してください。
例えば、プロジェクト名が `+hello_world+` の場合、現在の作業ディレクトリは `+hello_world+` のトップレベルのプロジェクトディレクトリかそのサブディレクトリのいずれかである必要があります。

== 基本的な利用法

[source,bash]
----
dfx ping [provider] [flag]
----

== フラグ

`+dfx ping+` コマンドでは、以下のオプションフラグを使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

== 引数

`+dfx ping+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数 |説明

|provider |使用したい {platform} またはテストネットの URL を指定します。
|===

== 例

以下のようなコマンドを実行することで、`+dfx ping+` コマンドを使用して，{IC} が現在特定のネットワークアドレスで利用可能かどうかを確認することができます：

[source,bash]
----
dfx ping https://testgw.dfinity.network
----

指定したネットワークプロバイダアドレスで {IC} が動作している場合、コマンドは次のような出力を返します。

....
{
  "ic_api_version": "0.8"
}
....



////
= dfx ping

Use the `+dfx ping+` command to check connectivity to the {platform} or a testnet.
This command enables you to verify that you can connect to the environment where you want to deploy to. 

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

== Basic usage

[source,bash]
----
dfx ping [provider] [flag]
----

== Flags

You can use the following optional flags with the `+dfx ping+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

== Arguments

You can specify the following argument for the `+dfx ping+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description

|provider |Specifies the {platform} or testnet URL that you want to use.
|===

== Examples

You can use the `+dfx ping+` command to check whether the {IC} is currently available at a specific network address by running a command similar to the following:

[source,bash]
----
dfx ping https://testgw.dfinity.network
----

If the {IC} is running on the specified network provider address, the command returns output similar to the following:

....
{
  "ic_api_version": "0.8"
}
....



////
