= dfx ledger

`+dfx ledger+` コマンドを使用して、「 Ledger Canister 」（台帳）と対話を行います。

このコマンドは、ユーティリティトークンである ICP をある Canister から別の Canister に移転するトランザクションや、ICP から（ミントされた） Cycle を Canister に追加したりするために使用されます。

`+dfx ledger+` コマンドを実行するための基本的な構文は以下のとおりです：

[source,bash]
----
dfx ledger [options] [subcommand]
----

指定する `+dfx ledger+` サブコマンドによっては、追加の引数、オプション、フラグが適用される場合があります。`+dfx ledger+` コマンドの使い方を説明するリファレンス情報と例については適切なコマンドを選択してご覧ください。

[width="100%",cols="<32%,<68%",options="header"]
|===
|コマンド |説明
|<<dfx ledger account-id,`+account-id+`>> |選択された開発者 Indentity のアカウント ID を表示します。
|<<dfx ledger balance,`+balance+`>> |ユーザー Identity のアカウント ID の残高を表示します。
|<<dfx ledger create-canister,`+create-canister+`>> |ICP から Canister を作成します。
|`+help+` |指定されたサブコマンドの使用情報メッセージを表示します。
|<<dfx ledger notify,`+notify+`>> |Cycle をミントする Canister への送信トランザクションがあった場合、台帳に通知します。
|<<dfx ledger top-up,`+top-up+`>> |ICP からミントする Cycle を Canister に追加します。
|<<dfx ledger transfer,`+transfer+`>> |ユーザー Identity から転送先のアカウント ID に ICP を転送します。
|===

特定のサブコマンドの使用情報を見るには、そのサブコマンドと `+--help+` フラグを指定します。
例えば、`+dfx ledger transfer+` の使用情報を見るには、以下のコマンドを実行します：

`+dfx ledger transfer --help+`

[[account-id]]
== dfx ledger account-id

現在、アクティブな Identity に関連付けられたアカウント ID を表示するには、`+dfx ledger account-id+` コマンドを使用します。
開発者 Identity の Principal のテキストタイプ表現と同様、アカウント ID は秘密鍵から派生したもので、Ledger Canister であなたの ID を表現するために使われます。

=== 基本的な利用法

[source,bash]
----
dfx ledger account-id [flag]
----

=== フラグ

以下のオプションフラグは `+dfx ledger account-id+` コマンドと一緒に使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 例

複数の Identity を作成した場合、`+dfx identity whoami+` コマンドまたは `+dfx identity get-principal+` コマンドを実行して、現在使用している Identity を確認します。次に、以下のコマンドを実行して、現在選択されている開発者 Identity のアカウント ID を確認できます：

[source,bash]
----
dfx ledger account-id
----

このコマンドは次のような出力を表示します：

....
03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
....

[[balance]]
== dfx ledger balance

`+dfx ledger balance+` コマンドは自分のアカウント残高や他のユーザーのアカウント残高を表示します。

=== 基本的な利用法

[source,bash]
----
dfx ledger --network ic balance [of] [flag]
----

=== フラグ

以下のオプションフラグは `+dfx ledger balance+` コマンドで使用できます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 引数

`+dfx ledger balance+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数 |説明
|`+<of>+` |残高を取得するアカウント ID を指定します。指定しない場合は、現在選択されているユーザー Identity （に紐づくアカウント）の ICP トークン残高を返します。
|===

=== 例

他のユーザーの残高を確認するには、`+dfx ledger balance+` コマンドを使用します。
例えば、以下のコマンドを実行すると、既知のアカウント ID に関連付けられた ICP トークンを確認することができます：

[source,bash]
----
dfx ledger --network ic balance 03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
----
このコマンドは次のような ICP 数量を表示します：

....
2.49798000 ICP
....

[[create-canister]]
== dfx ledger create-canister

`+dfx ledger create-canister+` コマンドを使用して、ICP トークンを Cycle に変換し、{IC} に新しい Canister ID を登録することができます。

=== 基本的な利用法

[source,bash,subs=quotes]
----
dfx ledger --network ic create-canister _controller_ [options]  [flag]
----

=== フラグ

`+dfx ledger create-canister+` コマンドには以下のオプションフラグを使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 引数

`+dfx ledger create-canister+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数 |説明
|`+<controller>+` |新しい Canister のコントローラーとして設定する Principal ID を指定します。
|===

=== オプション

`+dfx ledger create-canister+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|オプション |説明
|`+--amount <amount>+` |ICP トークンかミントされた Cycle を、送金先 Canister にデポジットする数量を指定します。金額は小数点以下8桁までの数字で指定できます。
|`+--e8s <e8s>+` |ICP トークンの分数単位（e8）を整数で指定します。例えば、1.05000000は1 ICP と5,000,000 e8s です。このオプションは単独で、あるいは `+--icp+` オプションと一緒に使用することができます。
|`+--fee <fee>+` |取引手数料を指定します。デフォルトは10,000 e8s です。
|`+--icp <icp>+` |ICP トークンを整数で指定します。このオプションは単独で、あるいは `+--e8s+` と組み合わせて使用することができます。
|`+--max-fee <max-fee>+` |取引手数料の上限を指定します。デフォルトは10,000 e8s です。
|===

=== 例

Cycle を扱える新しい Canister を作成するには、以下のようなコマンドを実行して、台帳アカウントから ICP トークンを転送します：

[source,bash]
----
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --amount 1.25
----

このコマンドは `+--amount+` 引数に指定した ICP トークンの数量を Cycle に変換し、指定した Principal で制御される新しい Canister ID に Cycle を関連付けます。

この例では、コマンドは 1.25 ICP トークンを Cycle に変換し、新しい Canister のコントローラーとして、デフォルトの Identity の Principal ID を指定しています。

トランザクションが成功すると、台帳にイベントが記録され、次のような出力が表示されるはずです。

....
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
....

以下のようなコマンドを実行して、ICP トークンと e8s に別々の値を指定することで、新しい Canister を作成することができます。

[source,bash]
----
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --icp 3 --e8s 5000
----

[[notify]]
== dfx ledger notify

`+dfx ledger notify+` コマンドを使用すると、Cycle をミントする Canister への送信トランザクションを台帳に通知します。
このコマンドは `+dfx ledger create-canister+` や `+dfx ledger top-up+` が台帳へのメッセージ送信に成功し、あるブロック高でトランザクションが記録されたが、何らかの理由でその後の通知に失敗した場合のみ使用されます。

=== 基本的な利用法

[source,bash,sub=quote]
----
dfx ledger notify [options] _block-height_ _destination-principal_
----

=== フラグ

`+dfx ledger notify+` コマンドでは以下のオプションフラグを使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 引数

`+dfx ledger notify+` コマンドでは以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数|説明
|`+<block-height>+` |送信トランザクションが記録されたブロック高を指定します。
|`+<destination-principal>+` |送信先の Principal を指定します。Canister ID またはユーザー Identity の Principal のテキストタイプ表現のいずれかを指定します。
送信トランザクションが `+create-canister+` コマンドの場合は、`+controller+` Principal を指定します。
送信トランザクションが `+top-up+` コマンドの場合、`+canister ID+` を指定します。
|===

=== 例

次の例は、ブロック高 `+75948+` で記録された `_send+` トランザクションのレスポンスとして `+notify+` メッセージを台帳に送信するものです。

[source,bash]
----
dfx ledger --network ic notify 75948 tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
----

[[top-up]]
== dfx ledger top-up

`+dfx ledger top-up+` コマンドでは、ICPトークンからミントされた Cycle を Canister に追加することができます。

=== 基本的な利用法

[source,bash,subs=quotes]
----
dfx ledger --network ic top-up [options] _canister_ [flag]
----

=== フラグ

`+dfx ledger top-up+` コマンドでは以下のオプションフラグが使用できます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 引数

`+dfx ledger top-up+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数 |説明
|`+canister+` |追加する Canister ID を指定します。
|===

=== オプション

`+dfx ledger top-up+` コマンドには以下のオプションを指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|オプション |説明
|`+--amount <amount>+` |ICP トークンかミントされた Cycle を、送金先 Canister にデポジットする数量を指定します。金額は小数点以下8桁までの数字で指定できます。
|`+--e8s <e8s>+` |ICP トークンの最小単位を e8 とし，小数点以下の単位を整数で指定します．例えば、1.05000000は1 ICPと5,000,000 e8s です。このオプションは単独で、あるいは `+--icp+` オプションと一緒に使用することができます。
|`+--fee <fee>+` |オペレーションの取引手数料を指定します。デフォルトは10,000 e8s です。
|`+--icp <icp>+` |ICP トークンを整数で指定します。このオプションは単独で、あるいは `+--e8s+` と組み合わせて使用することができます。
|`+--max-fee <max-fee>+` |取引手数料の上限を指定します。デフォルトは10,000 e8s です。
|===

=== 例

`+dfx ledger top-up+` コマンドを使用すると、自分が管理している ICP トークンの残高から、特定の Canister の Cycle を追加することができます。
Canister ID は Cycle を受け取ることができる 「Cycle Wallet Canister 」と関連付けられている必要があります。または、 link:../../interface-spec/index{outfilesuffix}[Internet Computer Interface Specification] に記載されているシステム API を使って Cycle を受け取る方法を実装するために、「Cycle Wallet Canister 」ではない Canister を変更することもできます。

例えば、以下のコマンドを実行すると、{IC} に配置された Cycle Wallet Canister に1 ICP 相当の Cycle を追加することができます：

[source,bash]
----
dfx ledger --network ic top-up --icp 1 5a46r-jqaaa-aaaaa-qaadq-cai
----
このコマンドは次のような出力を表示します：

....
Transfer sent at BlockHeight: 59482
Canister was topped up!
....

[[transfer]]
== dfx ledger transfer

`+dfx ledger transfer+` コマンドを使用すると、ICP トークンを Ledger Canister のアカウントアドレスから送信先アドレスに転送することができます。

=== 基本的な利用法

[source,bash,subs=quotes]
----
dfx ledger transfer [options] _to_ --memo _memo_
----

=== フラグ

`+dfx ledger transfer+` コマンドでは、以下のオプションフラグを使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

=== 引数

`+dfx ledger transfer+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|引数 |説明
|`+<to>+` |ICP トークンの送金先であるアカウント ID またはアドレスを指定します。
|===

=== オプション

`+dfx ledger transfer+` コマンドには以下の引数を指定することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|オプション |説明
|`+--amount <amount>+` |転送する ICP トークンの数量を指定します。
小数点以下8桁までの数値で指定可能です。
|`+--e8s <e8s>+` |e8s を整数で指定し，1 e8 を ICPトークンの最小値とする。例えば、1.05000000は1 ICPと5,000,000 e8s である。このオプションは単独で、あるいは `+--icp+` オプションと一緒に使用することができます。
|`+--fee <fee>+` |取引手数料を指定します。デフォルトは10,000 e8s です。
|`+--icp <icp>+` |ICP を整数で指定します。このオプションは単独で、または `+--e8s+` と組み合わせて使用することができます。
|`+--memo <memo>+` |このトランザクションの数値メモを指定します。
|===

=== 例

`+dfx ledger transfer+` コマンドを使用すると、転送先のアカウント ID に ICP を送信することができます。

例えば、以下のコマンドを実行すると、現在使用している Principal に関連するアカウント ID を確認することができます。

[source,bash]
----
dfx ledger account-id
----

このコマンドは、次のような出力を表示します：

....
30e596fd6c5ff5ad7b7d70bbbda1187c833e646c6251464da7f82bc217bba397
....

このアカウントの残高は以下のコマンドを実行することで確認することができます：

[source,bash]
----
dfx ledger --network ic balance
----

このコマンドは、次のような出力を表示します：

....
64.89580000 ICP
....

以下のコマンドを使用して、`+dfx ledger transfer+` コマンドで ICP 残高の一部を別の既知の送信先に送信してください。

[source,bash]
----
dfx ledger --network ic transfer dd81336dbfef5c5870e84b48405c7b229c07ad999fdcacb85b9b9850bd60766f --memo 12345 --icp 1
----

このコマンドは、次のような出力を表示します：

....
Transfer sent at BlockHeight: 59513
....

その後、`+dfx ledger --network ic balance+` コマンドを使用して、アカウント残高に今行った取引が反映されているかどうかを確認することができます。



////
= dfx ledger

Use the `+dfx ledger+` command to interact with the ledger canister.

This command can be used to make ICP utility token transactions from one canister to another, or top up canisters with cycles from ICP.

The basic syntax for running `+dfx ledger+` commands is:

[source,bash]
----
dfx ledger [options] [subcommand]
----

Depending on the `+dfx ledger+` subcommand you specify, additional arguments, options, and flags might apply. For reference information and examples that illustrate using `+dfx ledger+` commands, select an appropriate command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|<<dfx ledger account-id,`+account-id+`>> |Prints the selected identity's Account Identifier.
|<<dfx ledger balance,`+balance+`>> |Prints the account balance of the user.
|<<dfx ledger create-canister,`+create-canister+`>> |Creates a canister from ICP.
|`+help+` |Displays usage information message for a specified subcommand.
|<<dfx ledger notify,`+notify+`>> |Notifies the ledger when there is a send transaction to the cycles minting canister.
|<<dfx ledger top-up,`+top-up+`>> |Tops up a canister with cycles minted from ICP.
|<<dfx ledger transfer,`+transfer+`>> |Transfers ICP from the user to the destination Account Identifier.
|===

To view usage information for a specific subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx ledger transfer+`, you can run the following command:

`+dfx ledger transfer --help+`

[[account-id]]
== dfx ledger account-id

Use the `+dfx ledger account-id+` command to display the account identifier associated with the currently-active identity.
Like the textual representation of your developer identity principal, the account identifier is derived from your private key and used to represent your identity in the ledger canister.

=== Basic usage

[source,bash]
----
dfx ledger account-id [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger account-id+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

If you have created more than one identity, check the identity you are currently using by running the `+dfx identity whoami+` command or the `+dfx identity get-principal+` command. You can then check the account identifier for your currently-selected developer identity by running the following command:

[source,bash]
----
dfx ledger account-id
----

The command displays output similar to the following:

....
03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
....

[[balance]]
== dfx ledger balance

Use the `+dfx ledger balance+` command to print your account balance or that of another user.

=== Basic usage

[source,bash]
----
dfx ledger --network ic balance [of] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<of>+` |Specify an Account Identifier to get the balance. If this command is not specified, the command returns the balance of ICP tokens for the currently-selected user identity. 
|===

=== Examples

You can use the `+dfx ledger balance+` command to check the balance of another user.
For example, you can run the following command to see the ICP utlity tokens associated with a known Account Identifier:

[source,bash]
----
dfx ledger --network ic balance 03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
----
This command displays an ICP amount similar to the following:

....
2.49798000 ICP
....

[[create-canister]]
== dfx ledger create-canister

Use the `+dfx ledger create-canister+` command to convert ICP tokens to cycles and to register a new canister identifier on the {IC}.

=== Basic usage

[source,bash,subs=quotes]
----
dfx ledger --network ic create-canister _controller_ [options]  [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger create-canister+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger create-canister+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<controller>+` |Specifies the principal identifier to set as the controller of the new canister.
|===

=== Options

You can specify the following argument for the `+dfx ledger create-canister+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--amount <amount>+` |Specify the number of ICP tokens to mint into cycles and deposit into destination canister. You can specify an amount as a number with up to eight (8) decimal places.
|`+--e8s <e8s>+` |Specify ICP token fractional units—called e8s—as a whole number, where one e8 is smallest partition of an ICP token. For example, 1.05000000 is 1 ICP and 5000000 e8s. You can use this option on its own or in conjunction with the `+--icp+` option.
|`+--fee <fee>+` |Specify a transaction fee. The default is 10000 e8s.
|`+--icp <icp>+` |Specify ICP tokens as a whole number. You can use this option on its own or in conjunction with `+--e8s+`.
|`+--max-fee <max-fee>+` |Specify a maximum transaction fee. The default is 10000 e8s.
|===

=== Examples

To create a new canister with cycles, transfer ICP tokens from your ledger account by running a command similar to the following:

[source,bash]
----
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --amount 1.25
----

This command converts the number of ICP tokens you specify for the `+--amount+` argument into cycles, and associates the cycles with a new canister identifier controlled by the principal you specify.

In this example, the command converts 1.25 ICP tokens into cycles and specifies the principal identifier for the default identity as the controller of the new canister.

If the transaction is successful, the ledger records the event and you should see output similar to the following:

....
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
....

You can create a new canister by specifying separate values for ICP tokens and e8s by running a command similar to the following:

[source,bash]
----
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --icp 3 --e8s 5000
----

[[notify]]
== dfx ledger notify

Use the `+dfx ledger notify+` command to notify the ledger about a send transaction to the cycles minting canister.
This command should only be used if `+dfx ledger create-canister+` or `+dfx ledger top-up+` successfully sent a message to the ledger, and a transaction was recorded at some block height, but for some reason the subsequent notify failed.

=== Basic usage

[source,bash,sub=quote]
----
dfx ledger notify [options] _block-height_ _destination-principal_
----

=== Flags

You can use the following optional flags with the `+dfx ledger notify+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger notify+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument|Description
|`+<block-height>+` |Specifies the block height at which the send transaction was recorded.
|`+<destination-principal>+` |Specifies the principal of the destination, either a canister identifier or the textual representation of a user principal.
If the send transaction was for the `+create-canister+` command, specify the `+controller+` principal.
If the send transaction was for the `+top-up+` command, specify the `+canister ID+`.
|===

=== Examples

The following example illustrates sending a `+notify+` message to the ledger in response to a `_send+` transaction that was recorded at the block height `+75948+`.

[source,bash]
----
dfx ledger --network ic notify 75948 tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
----

[[top-up]]
== dfx ledger top-up

Use the `+dfx ledger top-up+` command to top up a canister with cycles minted from ICP tokens.

=== Basic usage

[source,bash,subs=quotes]
----
dfx ledger --network ic top-up [options] _canister_ [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger top-up+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger top-up+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+canister+` |Specifies the canister identifier that you would like to top up.
|===

=== Options

You can specify the following options for the `+dfx ledger top-up+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--amount <amount>+` |Specifies the number of ICP tokens to mint into cycles and deposit into the destination canister.
You can specify the amount as a number with up to eight (8) decimal places.
|`+--e8s <e8s>+` |Specifies fractional units of an ICP token—called e8s—as a whole number, where one e8 is the smallest unit of an ICP token. For example, 1.05000000 is 1 ICP and 5000000 e8s. You can use this option on its own or in conjunction with the `+--icp+` option.
|`+--fee <fee>+` |Specifies the transaction fee for the operation. The default is 10000 e8s.
|`+--icp <icp>+` |Specifies ICP tokens as a whole number. You can use this option on its own or  in conjunction with `+--e8s+`.
|`+--max-fee <max-fee>+` |Specifies a maximum transaction fee. The default is 10000 e8s.
|===

=== Examples

You can use the `+dfx ledger top-up+` command to top up the cycles of a specific canister from the balance of ICP tokens you control.
The canister identifier must be associated with a cycles wallet canister that is able to receive cycles. Alternatively, you can modify a non-cycles wallet canister to implement a method to receive cycles using system APIs described in the link:../../interface-spec/index{outfilesuffix}[Internet Computer Interface Specification].

For example, you can run the following command to top-up a cycles wallet canister deployed on the Internet Computer with 1 ICP worth of cycles:

[source,bash]
----
dfx ledger --network ic top-up --icp 1 5a46r-jqaaa-aaaaa-qaadq-cai
----
This command displays output similar to the following:

....
Transfer sent at BlockHeight: 59482
Canister was topped up!
....

[[transfer]]
== dfx ledger transfer

Use the `+dfx ledger transfer+` command to transfer ICP tokens from your account address in the ledger canister to a destination address.

=== Basic usage

[source,bash,subs=quotes]
----
dfx ledger transfer [options] _to_ --memo _memo_
----

=== Flags

You can use the following optional flags with the `+dfx ledger transfer+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger transfer+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<to>+` |Specify the Account Identifier or address to which you want to transfer ICP tokens.
|===

=== Options

You can specify the following argument for the `+dfx ledger transfer+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--amount <amount>+` |Specifies the number of ICP tokens to transfer.
Can be specified as a number with up to eight (8) decimal places.
|`+--e8s <e8s>+` |Specifies e8s as a whole number, where one e8 is smallest partition of an ICP token. For example, 1.05000000 is 1 ICP and 5000000 e8s. You can use this option alone or in conjunction with the `+--icp+` option.
|`+--fee <fee>+` |Specifies a transaction fee. The default is 10000 e8s.
|`+--icp <icp>+` |Specifies ICP as a whole number. You can use this option alone or in conjunction with `+--e8s+`.
|`+--memo <memo>+` |Specifies a numeric memo for this transaction.
|===

=== Examples

You can use the `+dfx ledger transfer+` command to send ICP to the Account Identifier of the destination.

For example, you can run the following command to check the account identifier associated with the principal you are currently using:

[source,bash]
----
dfx ledger account-id
----

This command displays output similar to the following:

....
30e596fd6c5ff5ad7b7d70bbbda1187c833e646c6251464da7f82bc217bba397
....

You can check the balance of this account by running the following command:

[source,bash]
----
dfx ledger --network ic balance
----

This command displays output similar to the following:

....
64.89580000 ICP
....

Use the `+dfx ledger transfer+` command to send some of your ICP balance to another known destination using the following command:

[source,bash]
----
dfx ledger --network ic transfer dd81336dbfef5c5870e84b48405c7b229c07ad999fdcacb85b9b9850bd60766f --memo 12345 --icp 1
----

This command displays output similar to the following:

....
Transfer sent at BlockHeight: 59513
....

You can then use the `+dfx ledger --network ic balance+` command to check that your account balance reflects the transaction you just made.



////
