= dfx start

`+dfx start+` コマンドを使用すると、現在のプロジェクトのローカル Canister 実行環境とWeb サーバープロセスを起動することができます。
このコマンドは、開発中のアプリをテストするために、ローカルの Canister 実行環境に Canister をデプロイすることを可能にします。

このコマンドは、プロジェクトのディレクトリ構造内からしか実行できないことに注意してください。
例えば、プロジェクト名が `+hello_world+` の場合、現在の作業ディレクトリは `+hello_world+` のトップレベルのプロジェクトディレクトリかそのサブディレクトリのいずれかである必要があります。

== 基本的な利用法

[source,bash]
----
dfx start [option] [flag]
----

== フラグ

`+dfx start+` コマンドでは、以下のオプションフラグを使用することができます。

[width="100%",cols="<32%,<68%",options="header"]
|===
|フラグ |説明
|`+--background+` |ローカル Canister の実行環境と Web サーバープロセスをバックグラウンドで起動し、応答を待ってシェルに戻ります。
|`+--clean+` |プロジェクト・キャッシュからチェックポイントを削除して、クリーンな状態でローカル Canister 実行環境と Web サーバープロセスを開始します。
このフラグは、トラブルシューティングやデバッグの際に、プロジェクト・キャッシュを新しい状態に設定するために使用できます。

|`+-h+`, `+--help+` |利用情報を表示します。
|`+-V+`, `+--version+` |バージョン情報を表示します。
|===

== オプション

`+dfx start+` コマンドで以下のオプションを使用することができます。

[width="100%",cols="<32%,<68%",options="header",]
|===
|オプション|説明
|`+--host host+` |フロントエンドをバインドするホストインターフェイスの IP アドレスとポート番号を指定します。デフォルトは `127.0.0.1:8000` です。
|===

== 例

以下のコマンドを実行することで、現在のシェルでローカル Canister 実行環境とWeb サーバープロセスを起動することができます：

[source,bash]
----
dfx start
----

現在のシェルでローカル Canister 実行環境を起動した場合、追加のコマンドを実行するために新しい ターミナルシェルを開く必要があります。
または、以下のコマンドを実行して、ローカル Canister 実行環境をバックグラウンドで起動することもできます：

[source,bash]
----
dfx start --background
----

ただし、ローカル Canister 実行環境をバックグラウンドで実行している場合は、`+dfx+` 実行環境をアンインストールまたは再インストールする前に、以下のコマンドを実行してローカル Canister 実行環境を必ず停止してください：

[source,bash]
----
dfx stop
----

以下のコマンドを実行することで、`+dfx+` で起動したローカル Canister 実行環境プロセスの現在のプロセス ID（ `+pid+` ）を確認することができます：

[source,bash]
----
more .dfx/pid
----



////
= dfx start

Use the `+dfx start+` command to start a local canister execution environment and web server processes for the current project.
This command enables you to deploy canisters to the local canister execution environment to test your dapps during development.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

== Basic usage

[source,bash]
----
dfx start [option] [flag]
----

== Flags

You can use the following optional flags with the `+dfx start+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+--background+` |Starts the local canister execution environment and web server processes in the background and waits for a reply before returning to the shell.

|`+--clean+` |Starts the local canister execution environment and web server processes in a clean state by removing checkpoints from your project cache.
You can use this flag to set your project cache to a new state when troubleshooting or debugging.

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

== Options

You can use the following option with the `+dfx start+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Option |Description
|`+--host host+` |Specifies the host interface IP address and port number to bind the frontend to. The default is `127.0.0.1:8000`.
|===

== Examples

You can start the local canister execution environment and web server processes in the current shell by running the following command:

[source,bash]
----
dfx start
----

If you start the local canister execution environment in the current shell, you need to open a new terminal shell to run additional commands.
Alternatively, you can start the local canister execution environment in the background by running the following command:

[source,bash]
----
dfx start --background
----

If you run the local canister execution environment in the background, however, be sure to stop the local canister execution environment before uninstalling or reinstalling the `+dfx+` execution environment by running the following command:

[source,bash]
----
dfx stop
----

You can view the current process identifier (`+pid+`) for  the local canister execution environment process started by `+dfx+`  by running the following command:

[source,bash]
----
more .dfx/pid
----



////
